=== harlantc/obscycle/prop/gov/sao/asc/obsed/data/formView.dtd
<?xml version="1.0" encoding="us-ascii"?>

<!ELEMENT formView (title,info,key,navigation,GUI)>

<!ELEMENT title (#PCDATA)>
<!ELEMENT info (supportsNew)>
<!ELEMENT supportsNew (#PCDATA)>
<!ELEMENT key (tableName, columnName)>
<!ELEMENT tableName (#PCDATA)>
<!ELEMENT columnName (#PCDATA)>

<!ELEMENT navigation (display+)>
<!ELEMENT display (name, tableName, columnName)>
<!ELEMENT name (#PCDATA)>

<!ELEMENT GUI (textfield | combobox | keycombobox | triplebox | obsidcombobox | obsidbutton | seqnbrbutton | separator | label | textarea | timestampbutton)+>
<!ELEMENT textfield (labelText, size?, row?, column?, database, anchor? )>
<!ATTLIST textfield tag ID #REQUIRED>
<!ELEMENT labelText (#PCDATA)>
<!ELEMENT size (#PCDATA)>
<!ELEMENT row (number, height)>
<!ELEMENT number (#PCDATA)>
<!ELEMENT height (#PCDATA)>
<!ELEMENT column (number, width)>
<!ELEMENT width (#PCDATA)>
<!ELEMENT database (tableName, columnName, joinTableName?, joinColumnName?, queryString?)>
<!ELEMENT keyinfo (keyTableName, keyColumnName)>
<!ELEMENT combobox (labelText, size?, row?, column?, database, null?, anchor?)>
<!ATTLIST combobox tag ID #REQUIRED none (true | false) "true" new (true | false) "false">
<!ELEMENT keycombobox (labelText, size?, row?, column?, database, keyinfo, null?, anchor?)>
<!ATTLIST keycombobox tag ID #REQUIRED new (true | false) "false" none (true | false) "true">
<!ELEMENT triplebox (labelText, row?, column?, database, null?, anchor?)>
<!ATTLIST triplebox tag ID #REQUIRED>
<!ELEMENT obsidcombobox (labelText, row?, column?, database, null?, anchor?)>
<!ATTLIST obsidcombobox tag ID #REQUIRED>
<!ELEMENT obsidbutton (labelText, row?, column?, database, anchor? )>
<!ATTLIST obsidbutton tag ID #REQUIRED>
<!ELEMENT seqnbrbutton (labelText, row?, column?, database, anchor? )>
<!ATTLIST seqnbrbutton tag ID #REQUIRED>
<!ELEMENT separator EMPTY>
<!ELEMENT label (labelText, anchor?, row?, column?)>
<!ELEMENT null (representation, value?)>
<!ELEMENT representation (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT anchor (#PCDATA)>
<!ELEMENT textarea (labelText, size?, row?, column?, database, anchor?)>
<!ATTLIST textarea tag ID #REQUIRED>
<!ELEMENT timestampbutton (labelText, row?, column?, database, anchor? )>
<!ATTLIST timestampbutton tag ID #REQUIRED>

<!ELEMENT constraintList (constraint+)>
<!ELEMENT constraint (entry | grating | firstOrderCountRate | yOffset | zOffset | radial | instrument | type | ra | dec | ssObject | angle| tolerance | startTime | stopTime | photometry | visualMag)>
<!ATTLIST constraint type ID #REQUIRED>
<!ELEMENT entry (#PCDATA)>
<!ELEMENT grating (#PCDATA)>
<!ELEMENT firstOrderCountRate (#PCDATA)>
<!ELEMENT yOffset (#PCDATA)>
<!ELEMENT zOffset (#PCDATA)>
<!ELEMENT radial (#PCDATA)>
<!ELEMENT instrument (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT ra (#PCDATA)>
<!ELEMENT dec (#PCDATA)>
<!ELEMENT ssObject (#PCDATA)>
<!ELEMENT angle (#PCDATA)>
<!ELEMENT tolerance (#PCDATA)>
<!ELEMENT startTime (#PCDATA)>
<!ELEMENT stopTime (#PCDATA)>
<!ELEMENT photometry (#PCDATA)>
<!ELEMENT visualMag (#PCDATA)>

=== harlantc/obscycle/prop/gov/sao/asc/obsed/data/prop_infoFormView.xml
<?xml version="1.0" encoding="us-ascii"?>

<!DOCTYPE formView SYSTEM "formView.dtd">

<formView>

  <title>Prop Info Form</title>

  <info>
    <supportsNew>noDelete</supportsNew>
  </info>

  <key>
    <tableName>prop_info</tableName>
    <columnName>ocat_propid</columnName>
  </key>

  <navigation>
    <display>
	<name>ObsCat Prop. Id</name>
	<tableName>prop_info</tableName>
	<columnName>ocat_propid</columnName>
    </display>
    <display>
	<name>Proposal Number</name>
	<tableName>prop_info</tableName>
	<columnName>prop_num</columnName>
    </display>
  </navigation>

  <GUI>

    <textfield tag="11">
      <labelText>ObsCat Prop. Id</labelText>
      <size>6</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
	<tableName>prop_info</tableName>
	<columnName>ocat_propid</columnName>
      </database>
    </textfield>

    <textfield tag="12">
      <labelText>Proposal Number</labelText>
      <size>6</size>
      <database>
	<tableName>prop_info</tableName>
	<columnName>prop_num</columnName>
      </database>
    </textfield>
    
    <textfield tag="13">
      <labelText>Proposal Id</labelText>
      <size>6</size>
      <database>
        <tableName>prop_info</tableName>
        <columnName>proposal_id</columnName>
      </database>
    </textfield>
    
    <textfield tag="21">
      <labelText>Title</labelText>
      <size>56</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
        <width>></width>
      </column>
      <database>
        <tableName>prop_info</tableName>
        <columnName>title</columnName>
      </database>
    </textfield>
    
    <combobox tag="31">
      <labelText>Category</labelText>
      <size>12</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
        <width>></width>
      </column>
      <database>
        <tableName>prop_info</tableName>
        <columnName>description</columnName>
      </database>
    </combobox>

    <combobox tag="42">
      <labelText>NRA Cycle#</labelText>
      <size>6</size>
      <database>
        <tableName>prop_info</tableName>
        <columnName>ao_str</columnName>
      </database>
    </combobox>
    
    <textfield tag="43">
      <labelText>Proposal Type</labelText>
      <size>20</size>
      <database>
        <tableName>prop_info</tableName>
        <columnName>proposal_type</columnName>
      </database>
    </textfield>
    
    <textfield tag="42">
      <labelText>P.I. Last</labelText>
      <size>24</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>view_pi</tableName>
        <columnName>last</columnName>
        <joinTableName>prop_info</joinTableName>
        <joinColumnName>ocat_propid</joinColumnName>
      </database>
    </textfield>

    <combobox tag="41">
      <labelText>PI Id</labelText>
      <size>8</size>
      <database>
        <tableName>prop_info</tableName>
	<columnName>piid</columnName>
      </database>
    </combobox>

    <combobox tag="50">
      <labelText>Joint Policy</labelText>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <size>8</size>
      <database>
        <tableName>prop_info</tableName>
        <columnName>joint</columnName>
      </database>
    </combobox>


    <textfield tag="13">
      <labelText>HST Orbits</labelText>
      <size>6</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>prop_info</tableName>
        <columnName>hst_approved_time</columnName>
      </database>
    </textfield>

    <textfield tag="13">
      <labelText>XMM Time</labelText>
      <size>6</size>
      <database>
        <tableName>prop_info</tableName>
        <columnName>xmm_approved_time</columnName>
      </database>
    </textfield>

    <textfield tag="71">
      <labelText>RXTE Time</labelText>
      <size>6</size>
      <database>
        <tableName>prop_info</tableName>
        <columnName>rxte_approved_time</columnName>
      </database>
    </textfield>
    

    <textfield tag="71">
      <labelText>Spitzer Hours</labelText>
      <size>6</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>prop_info</tableName>
        <columnName>spitzer_approved_time</columnName>
      </database>
    </textfield>

    <textfield tag="72">
      <labelText>Suzaku Time</labelText>
      <size>6</size>
      <database>
        <tableName>prop_info</tableName>
        <columnName>suzaku_approved_time</columnName>
      </database>
    </textfield>

    <textfield tag="73">
      <labelText>Swift Time</labelText>
      <size>6</size>
      <database>
        <tableName>prop_info</tableName>
        <columnName>swift_approved_time</columnName>
      </database>
    </textfield>

    <textfield tag="71">
      <labelText>NRAO Hours</labelText>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <size>6</size>
      <database>
        <tableName>prop_info</tableName>
        <columnName>nrao_approved_time</columnName>
      </database>
    </textfield>

    <textfield tag="13">
      <labelText>NOAO Nights</labelText>
      <size>6</size>
      <database>
        <tableName>prop_info</tableName>
        <columnName>noao_approved_time</columnName>
      </database>
    </textfield>

    <textfield tag="14">
      <labelText>NuSTAR Time </labelText>
      <size>6</size>
      <database>
        <tableName>prop_info</tableName>
        <columnName>nustar_approved_time</columnName>
      </database>
    </textfield>


    <combobox tag="62" none="false">
      <labelText>Medium</labelText>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <size>6</size>
      <database>
        <tableName>prop_info</tableName>
        <columnName>medium</columnName>
      </database>
    </combobox>
    
    
    <triplebox tag="51">
      <labelText>CoInvestigator</labelText>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>prop_info</tableName>
        <columnName>coi_contact</columnName>
      </database>
    </triplebox>
    
    <keycombobox tag="52">
      <labelText>Co-I Id</labelText>
      <size>6</size>
      <database>
        <tableName>prop_info</tableName>
        <columnName>coin_id</columnName>
      </database>
      <keyinfo>
        <keyTableName>axafusers..person_short</keyTableName>
        <keyColumnName>pers_id</keyColumnName>
      </keyinfo>
    </keycombobox>
    
    <textfield tag="2933" new="true">
      <labelText>CoI Name</labelText>
      <size>12</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>axafusers..person_short</tableName>
        <columnName>last</columnName>
        <joinTableName>prop_info</joinTableName>
        <joinColumnName>coin_id</joinColumnName>
      </database>
    </textfield>


    <textfield tag="53" new="true">
      <labelText>Co-I Phone</labelText>
      <size>12</size>
      <column>
        <number>.</number>
	<width>2</width>
      </column>
      <database>
        <tableName>prop_info</tableName>
        <columnName>coi_phone</columnName>
      </database>
    </textfield>
    

    <textarea tag="71">
      <labelText>Abstract</labelText>
      <size>56</size>
      <row>
        <number>+</number>
	<height>8</height>
      </row>
      <column>
        <number>0</number>
        <width>></width>
      </column>
      <database>
        <tableName>prop_info</tableName>
        <columnName>abstract</columnName>
      </database>
    </textarea>

  </GUI>

</formView>

=== harlantc/obscycle/prop/gov/sao/asc/obsed/data/grant_recipientFormView.xml
<?xml version="1.0" encoding="us-ascii"?>

<!DOCTYPE formView SYSTEM "formView.dtd">

<formView>

  <title>Grant Recipient Form</title>

  <info>
    <supportsNew>nil</supportsNew>
  </info>

  <key>
    <tableName>grant_recipient</tableName>
    <columnName>id</columnName>
  </key>

  <navigation>
    <display>
      <name>Grant Recipient Id</name>
      <tableName>grant_recipient</tableName>
      <columnName>id</columnName>
    </display>
   <display>
      <name>Grant Id+i Recipient Id</name>
      <tableName>grant_recipient</tableName>
      <columnName>(convert(char(10),grant_id)+convert(char(10),id))</columnName>
    </display>
  </navigation>

  <GUI>
    <textfield tag="11">
      <labelText>Id</labelText>
      <size>8</size>
      <database>
        <tableName>grant_recipient</tableName>
	<columnName>id</columnName>
      </database>
     </textfield>

    <keycombobox tag="33">
      <labelText>Grant Id</labelText>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <size>10</size>
      <database>
        <tableName>grant_recipient</tableName>
	<columnName>grant_id</columnName>
      </database>
      <keyinfo>
	<keyTableName>grant_info</keyTableName>
	<keyColumnName>grant_id</keyColumnName>
      </keyinfo>
    </keycombobox>

    <textfield tag="34">
      <labelText>Grant Number</labelText>
      <size>8</size>
      <database>
        <tableName>view_grants</tableName>
        <columnName>grant_number</columnName>
        <joinTableName>grant_recipient</joinTableName>
        <joinColumnName>grant_id</joinColumnName>
      </database>
    </textfield>

    <keycombobox tag="43" >
      <labelText>Person Id</labelText>
      <size>8</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>grant_recipient</tableName>
	<columnName>pers_id</columnName>
      </database>
      <keyinfo>
	<keyTableName>axafusers..person_short</keyTableName>
	<keyColumnName>pers_id</keyColumnName>
      </keyinfo>
     <null>
        <representation>NULL</representation>
      </null>

    </keycombobox>

    <textfield tag="44">
      <labelText>Recipient </labelText>
      <size>8</size>
      <database>
        <tableName>axafusers..person_short</tableName>
        <columnName>last</columnName>
        <joinTableName>grant_recipient</joinTableName>
        <joinColumnName>pers_id</joinColumnName>
      </database>
    </textfield>
    
  </GUI>

</formView>

=== harlantc/obscycle/prop/gov/sao/asc/obsed/data/simFormView.xml
<?xml version="1.0" encoding="us-ascii"?>

<!DOCTYPE formView SYSTEM "formView.dtd">

<formView>

  <title>SIM Form</title>

  <info>
    <supportsNew>clone null</supportsNew>
  </info>

  <key>
    <tableName>sim</tableName>
    <columnName>obsid</columnName>
  </key>

  <navigation>
    <display>
      <name>Observation ID</name>
      <tableName>sim</tableName>
      <columnName>obsid</columnName>
    </display>
  </navigation>

  <GUI>
    <textfield tag="11">
      <labelText>OBS ID</labelText>
      <size>6</size>
      <database>
        <tableName>sim</tableName>
        <columnName>obsid</columnName>
      </database>
      <row>
        <number>0</number>
      </row>
      <column>
        <number>0</number>
      </column>
    </textfield>

    <textfield tag="12">
      <labelText>Trans Offset</labelText>
      <size>6</size>
      <database>
        <tableName>sim</tableName>
        <columnName>trans_offset</columnName>
      </database>
    </textfield>
    
    <textfield tag="13">
      <labelText>Focus Offset</labelText>
      <size>6</size>
      <database>
        <tableName>sim</tableName>
        <columnName>focus_offset</columnName>
      </database>
    </textfield>

  </GUI>

</formView>

=== harlantc/obscycle/prop/gov/sao/asc/obsed/data/mt_ephemNewView.xml
<?xml version="1.0" encoding="us-ascii"?>

<!DOCTYPE formView SYSTEM "formView.dtd">

<formView>

  <title>New Orbit Form</title>

  <info>
    <supportsNew>true</supportsNew>
  </info>

  <key>
    <tableName>mt_ephem</tableName>
    <columnName>obsid</columnName>
  </key>

  <navigation>
    <display>
      <name>Observation ID</name>
      <tableName>mt_ephem</tableName>
      <columnName>obsid</columnName>
    </display>
  </navigation>

  <GUI>
    <obsidcombobox tag="11">
      <labelText>Obs ID</labelText>
      <size>8</size>
      <row>
        <number>0</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>mt_ephem</tableName>
        <columnName>obsid</columnName>
	<queryString>SELECT target.obsid FROM target WHERE target.obj_flag = 'MT' AND NOT EXISTS (SELECT 1 FROM locked WHERE locked.obsid = target.obsid) AND NOT EXISTS (SELECT 1 FROM mt_ephem WHERE mt_ephem.obsid = target.obsid)</queryString>
      </database>
    </obsidcombobox>
    
    <textfield tag="21">
      <labelText>Epoch</labelText>
      <size>8</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>mt_ephem</tableName>
        <columnName>epoch</columnName>
      </database>
    </textfield>
    
    <textfield tag="22">
      <labelText>Semi-major Axis</labelText>
      <size>8</size>
      <database>
        <tableName>mt_ephem</tableName>
        <columnName>axis</columnName>
      </database>
    </textfield>
    
    <textfield tag="23">
      <labelText>Eccentricity</labelText>
      <size>8</size>
      <database>
        <tableName>mt_ephem</tableName>
        <columnName>eccentricity</columnName>
      </database>
    </textfield>

    <textfield tag="31">
      <labelText>Inclination</labelText>
      <size>8</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
        <width>></width>
      </column>
      <database>
        <tableName>mt_ephem</tableName>
        <columnName>eccentricity</columnName>
      </database>
    </textfield>
    
    <textfield tag="32">
      <labelText>RA of Ascending Node</labelText>
      <size>8</size>
      <database>
        <tableName>mt_ephem</tableName>
        <columnName>raan</columnName>
      </database>
    </textfield>
    
    <textfield tag="33">
      <labelText>Arg of Periastron</labelText>
      <size>8</size>
      <database>
        <tableName>mt_ephem</tableName>
        <columnName>aop</columnName>
      </database>
    </textfield>
    
    <textfield tag="41">
      <labelText>Mean Anomaly at Epoch</labelText>
      <size>8</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>mt_ephem</tableName>
        <columnName>ma</columnName>
      </database>
    </textfield>
  </GUI>

</formView>

=== harlantc/obscycle/prop/gov/sao/asc/obsed/data/grant_infoFormView.xml
<?xml version="1.0" encoding="us-ascii"?>

<!DOCTYPE formView SYSTEM "formView.dtd">

<formView>

  <title>Grant Info Form</title>

  <info>
    <supportsNew>nil</supportsNew>
  </info>

  <key>
    <tableName>grant_info</tableName>
    <columnName>grant_id</columnName>
  </key>

  <navigation>
    <display>
      <name>Grant Info Id</name>
      <tableName>grant_info</tableName>
      <columnName>grant_id</columnName>
    </display>
    <display>
      <name>Grant Number</name>
      <tableName>grant_info</tableName>
      <columnName>grant_number</columnName>
    </display>
  </navigation>

  <GUI>
    <textfield tag="11">
      <labelText>Grant Id</labelText>
      <size>8</size>
      <row>
        <number>0</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>grant_info</tableName>
        <columnName>grant_id</columnName>
      </database>
    </textfield>
    
    <textfield tag="12">
      <labelText>Grant Number</labelText>
      <size>20</size>
      <database>
        <tableName>grant_info</tableName>
        <columnName>grant_number</columnName>
      </database>
    </textfield>

    <textfield tag="22">
      <labelText>AO</labelText>
      <size>10</size>
      <database>
        <tableName>grant_info</tableName>
        <columnName>grant_ao</columnName>
      </database>
    </textfield>

    <textfield tag="32">
      <labelText>Grant Amount</labelText>
      <size>12</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>grant_info</tableName>
        <columnName>grant_amount</columnName>
      </database>
    </textfield>

    <textfield tag="31">
      <labelText>Grantor</labelText>
      <size>20</size>
      <database>
        <tableName>grant_info</tableName>
        <columnName>grantor</columnName>
      </database>
    </textfield>
    
    <textfield tag="21">
      <labelText>Type</labelText>
      <size>25</size>
      <database>
        <tableName>grant_info</tableName>
        <columnName>grant_type</columnName>
      </database>
    </textfield>




    <keycombobox tag="33">
      <labelText>Ocat Prop Id</labelText>
      <size>8</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>grant_info</tableName>
	<columnName>ocat_propid</columnName>
      </database>
      <keyinfo>
	<keyTableName>prop_info</keyTableName>
	<keyColumnName>ocat_propid</keyColumnName>
      </keyinfo>
    </keycombobox>

    <textfield tag="13">
      <labelText>Proposal Number</labelText>
      <size>8</size>
      <database>
        <tableName>prop_info</tableName>
        <columnName>prop_num</columnName>
        <joinTableName>grant_info</joinTableName>
        <joinColumnName>ocat_propid</joinColumnName>
      </database>
    </textfield>

    

    <textarea tag="22">
      <labelText>Proposal Title</labelText>
      <size>60</size>
      <row>
        <number>+</number>
	<height>2</height>
      </row>
      <column>
        <number>0</number>
        <width>></width>
      </column>
      <database>
        <tableName>prop_info</tableName>
        <columnName>title</columnName>
        <joinTableName>grant_info</joinTableName>
        <joinColumnName>ocat_propid</joinColumnName>
      </database>
    </textarea>

   <textarea tag="71">
      <labelText>Abstract</labelText>
      <size>60</size>
      <row>
        <number>+</number>
	<height>8</height>
      </row>
      <column>
        <number>0</number>
        <width>></width>
      </column>
      <database>
        <tableName>prop_info</tableName>
        <columnName>abstract</columnName>
        <joinTableName>grant_info</joinTableName>
        <joinColumnName>ocat_propid</joinColumnName>
      </database>
    </textarea>

    
  </GUI>

</formView>

=== harlantc/obscycle/prop/gov/sao/asc/obsed/data/soeFormView.xml
<?xml version="1.0" encoding="us-ascii"?>

<!DOCTYPE formView SYSTEM "formView.dtd">

<formView>

  <title>SOE Form</title>

  <info>
    <supportsNew>nil</supportsNew>
  </info>

  <key>
    <tableName>soe</tableName>
    <columnName>row_id</columnName>
  </key>

  <navigation>
    <display>
      <name>Observation ID</name>
      <tableName>soe</tableName>
      <columnName>obsid</columnName>
    </display>
  </navigation>

  <GUI>
    <label tag="11">
      <labelText>SOE</labelText>
      <row>
        <number>0</number>
      </row>
      <column>
        <number>0</number>
      </column>
    </label>

   <textfield tag="21">
      <labelText>Counter</labelText>
      <size>8</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>soe</tableName>
	<columnName>counter</columnName>
      </database>
    </textfield>

   <textfield tag="22">
      <labelText>Sequence Number</labelText>
      <size>8</size>
      <database>
        <tableName>soe</tableName>
	<columnName>seq_nbr</columnName>
      </database>
    </textfield>

   <textfield tag="23">
      <labelText>Observation Interval</labelText>
      <size>8</size>
      <database>
        <tableName>soe</tableName>
	<columnName>obi</columnName>
      </database>
    </textfield>

   <timestampbutton tag="31">
      <labelText>Start Scheduled Time</labelText>
      <size>18</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>soe</tableName>
	<columnName>st_sched_date</columnName>
      </database>
    </timestampbutton>

   <timestampbutton tag="32">
      <labelText>End Scheduled Time</labelText>
      <size>18</size>
      <database>
        <tableName>soe</tableName>
	<columnName>end_sched_date</columnName>
      </database>
    </timestampbutton>

   <textfield tag="41">
      <labelText>Scheduled Exposure Time</labelText>
      <size>8</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>soe</tableName>
	<columnName>sched_exp_time</columnName>
      </database>
    </textfield>

   <textfield tag="42">
      <labelText>Scheduled Roll Angle</labelText>
      <size>8</size>
      <database>
        <tableName>soe</tableName>
	<columnName>soe_roll</columnName>
      </database>
    </textfield>

   <textfield tag="51">
      <labelText>Quaternion 0</labelText>
      <size>10</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>soe</tableName>
	<columnName>quat0</columnName>
      </database>
    </textfield>

   <textfield tag="52">
      <labelText>Quaternion 1</labelText>
      <size>10</size>
      <database>
        <tableName>soe</tableName>
	<columnName>quat1</columnName>
      </database>
    </textfield>

   <textfield tag="53">
      <labelText>Quaternion 2</labelText>
      <size>10</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>soe</tableName>
	<columnName>quat2</columnName>
      </database>
    </textfield>

   <textfield tag="54">
      <labelText>Quaternion 3</labelText>
      <size>10</size>
      <database>
        <tableName>soe</tableName>
	<columnName>quat3</columnName>
      </database>
    </textfield>

   <textfield tag="61">
      <labelText>Type</labelText>
      <size>8</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>soe</tableName>
	<columnName>rec_id</columnName>
      </database>
    </textfield>

   <textfield tag="62">
      <labelText>Request Id</labelText>
      <size>8</size>
      <database>
        <tableName>soe</tableName>
	<columnName>req_id</columnName>
      </database>
    </textfield>

   <textfield tag="20">
      <labelText>Row Id</labelText>
      <size>8</size>
      <database>
        <tableName>soe</tableName>
	<columnName>row_id</columnName>
      </database>
    </textfield>

 </GUI>

</formView>

=== harlantc/obscycle/prop/gov/sao/asc/obsed/data/ditherNewView.xml
<?xml version="1.0" encoding="us-ascii"?>

<!DOCTYPE formView SYSTEM "formView.dtd">

<formView>
  <title>New Dither</title>

  <info>
    <supportsNew>true</supportsNew>
  </info>

  <key>
    <tableName>dither</tableName>
    <columnName>obsid</columnName>
  </key>

  <navigation>
    <display>
      <name>Observation ID</name>
      <tableName>dither</tableName>
      <columnName>obsid</columnName>
    </display>
  </navigation>

  <GUI>
    <obsidcombobox tag="11">
      <labelText>Obs ID</labelText>
      <size>6</size>
      <row>
        <number>0</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>dither</tableName>
        <columnName>obsid</columnName>
	<queryString>SELECT target.obsid FROM target WHERE NOT EXISTS (SELECT 1 FROM locked WHERE locked.obsid = target.obsid) AND NOT EXISTS (SELECT 1 FROM dither WHERE dither.obsid = target.obsid)</queryString>
      </database>
    </obsidcombobox>
    
    <textfield tag="21">
      <labelText>Y Amp</labelText>
      <size>8</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>dither</tableName>
        <columnName>y_amp</columnName>
      </database>
    </textfield>
    
    <textfield tag="22">
      <labelText>Y Freq</labelText>
      <size>8</size>
      <database>
        <tableName>dither</tableName>
        <columnName>y_freq</columnName>
      </database>
    </textfield>

    <textfield tag="23">
      <labelText>Y Phase</labelText>
      <size>8</size>
      <database>
        <tableName>dither</tableName>
        <columnName>y_phase</columnName>
      </database>
    </textfield>

    <textfield tag="31">
      <labelText>Z Amp</labelText>
      <size>8</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>dither</tableName>
        <columnName>z_amp</columnName>
      </database>
    </textfield>
    
    <textfield tag="32">
      <labelText>Z Freq</labelText>
      <size>8</size>
      <database>
        <tableName>dither</tableName>
        <columnName>z_freq</columnName>
      </database>
    </textfield>

    <textfield tag="33">
      <labelText>Z Phase</labelText>
      <size>8</size>
      <database>
        <tableName>dither</tableName>
        <columnName>z_phase</columnName>
      </database>
    </textfield>

  </GUI>

</formView>
