=== harlantc/obscycle/prop/gov/sao/asc/obsed/data/formView.dtd
<?xml version="1.0" encoding="us-ascii"?>

<!ELEMENT formView (title,info,key,navigation,GUI)>

<!ELEMENT title (#PCDATA)>
<!ELEMENT info (supportsNew)>
<!ELEMENT supportsNew (#PCDATA)>
<!ELEMENT key (tableName, columnName)>
<!ELEMENT tableName (#PCDATA)>
<!ELEMENT columnName (#PCDATA)>

<!ELEMENT navigation (display+)>
<!ELEMENT display (name, tableName, columnName)>
<!ELEMENT name (#PCDATA)>

<!ELEMENT GUI (textfield | combobox | keycombobox | triplebox | obsidcombobox | obsidbutton | seqnbrbutton | separator | label | textarea | timestampbutton)+>
<!ELEMENT textfield (labelText, size?, row?, column?, database, anchor? )>
<!ATTLIST textfield tag ID #REQUIRED>
<!ELEMENT labelText (#PCDATA)>
<!ELEMENT size (#PCDATA)>
<!ELEMENT row (number, height)>
<!ELEMENT number (#PCDATA)>
<!ELEMENT height (#PCDATA)>
<!ELEMENT column (number, width)>
<!ELEMENT width (#PCDATA)>
<!ELEMENT database (tableName, columnName, joinTableName?, joinColumnName?, queryString?)>
<!ELEMENT keyinfo (keyTableName, keyColumnName)>
<!ELEMENT combobox (labelText, size?, row?, column?, database, null?, anchor?)>
<!ATTLIST combobox tag ID #REQUIRED none (true | false) "true" new (true | false) "false">
<!ELEMENT keycombobox (labelText, size?, row?, column?, database, keyinfo, null?, anchor?)>
<!ATTLIST keycombobox tag ID #REQUIRED new (true | false) "false" none (true | false) "true">
<!ELEMENT triplebox (labelText, row?, column?, database, null?, anchor?)>
<!ATTLIST triplebox tag ID #REQUIRED>
<!ELEMENT obsidcombobox (labelText, row?, column?, database, null?, anchor?)>
<!ATTLIST obsidcombobox tag ID #REQUIRED>
<!ELEMENT obsidbutton (labelText, row?, column?, database, anchor? )>
<!ATTLIST obsidbutton tag ID #REQUIRED>
<!ELEMENT seqnbrbutton (labelText, row?, column?, database, anchor? )>
<!ATTLIST seqnbrbutton tag ID #REQUIRED>
<!ELEMENT separator EMPTY>
<!ELEMENT label (labelText, anchor?, row?, column?)>
<!ELEMENT null (representation, value?)>
<!ELEMENT representation (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT anchor (#PCDATA)>
<!ELEMENT textarea (labelText, size?, row?, column?, database, anchor?)>
<!ATTLIST textarea tag ID #REQUIRED>
<!ELEMENT timestampbutton (labelText, row?, column?, database, anchor? )>
<!ATTLIST timestampbutton tag ID #REQUIRED>

<!ELEMENT constraintList (constraint+)>
<!ELEMENT constraint (entry | grating | firstOrderCountRate | yOffset | zOffset | radial | instrument | type | ra | dec | ssObject | angle| tolerance | startTime | stopTime | photometry | visualMag)>
<!ATTLIST constraint type ID #REQUIRED>
<!ELEMENT entry (#PCDATA)>
<!ELEMENT grating (#PCDATA)>
<!ELEMENT firstOrderCountRate (#PCDATA)>
<!ELEMENT yOffset (#PCDATA)>
<!ELEMENT zOffset (#PCDATA)>
<!ELEMENT radial (#PCDATA)>
<!ELEMENT instrument (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT ra (#PCDATA)>
<!ELEMENT dec (#PCDATA)>
<!ELEMENT ssObject (#PCDATA)>
<!ELEMENT angle (#PCDATA)>
<!ELEMENT tolerance (#PCDATA)>
<!ELEMENT startTime (#PCDATA)>
<!ELEMENT stopTime (#PCDATA)>
<!ELEMENT photometry (#PCDATA)>
<!ELEMENT visualMag (#PCDATA)>

=== harlantc/obscycle/prop/gov/sao/asc/obsed/data/aciswinFormView.xml
<?xml version="1.0" encoding="us-ascii"?>

<!DOCTYPE formView SYSTEM "formView.dtd">

<formView>

  <title>ACISWIN Form</title>

  <info>
    <supportsNew>clone null</supportsNew>
  </info>

  <key>
    <tableName>aciswin</tableName>
    <columnName>aciswin_id</columnName>
  </key>

  <navigation>
    <display>
      <name>ACISWIN Identifier</name>
      <tableName>aciswin</tableName>
      <columnName>aciswin_id</columnName>
    </display>
    <display>
      <name>ObsId+Chip+Order</name>
      <tableName>aciswin</tableName>
      <columnName>(convert(char(8),obsid)+convert(char(4),chip)+convert(char(8),ordr))</columnName>
    </display>

  </navigation>

  <GUI>
    <label tag="11">
      <labelText>ACISWIN</labelText>
      <row>
        <number>0</number>
      </row>
      <column>
        <number>0</number>
      </column>
    </label>

    <textfield tag="12">
      <labelText>Id</labelText>
      <size>6</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>aciswin</tableName>
        <columnName>aciswin_id</columnName>
      </database>
    </textfield>


    <textfield tag="13">
      <labelText>Obs Id</labelText>
      <size>6</size>
      <database>
        <tableName>aciswin</tableName>
        <columnName>obsid</columnName>
      </database>
    </textfield>
    
    <textfield tag="21" >
      <labelText>Order</labelText>
      <size>2</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>aciswin</tableName>
        <columnName>ordr</columnName>
      </database>
    </textfield>
    
    <combobox tag="22" none="false">
      <labelText>Chip</labelText>
      <size>6</size>
      <database>
        <tableName>aciswin</tableName>
	<columnName>chip</columnName>
      </database>
    </combobox>

    <combobox tag="23" none="false">
      <labelText>Include Flag</labelText>
      <database>
        <tableName>aciswin</tableName>
	<columnName>include_flag</columnName>
      </database>
    </combobox>

    <textfield tag="31" >
      <labelText>Start Row</labelText>
      <size>5</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>aciswin</tableName>
	<columnName>start_row</columnName>
      </database>
    </textfield>

    <textfield tag="32">
      <labelText>Start Column</labelText>
      <size>5</size>
      <database>
        <tableName>aciswin</tableName>
	<columnName>start_column</columnName>
      </database>
    </textfield>

    <textfield tag="41">
      <labelText>Height</labelText>
      <size>10</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>aciswin</tableName>
	<columnName>height</columnName>
      </database>
    </textfield>

    <textfield tag="42">
      <labelText>Width</labelText>
      <size>10</size>
      <database>
        <tableName>aciswin</tableName>
	<columnName>width</columnName>
      </database>
    </textfield>

    <textfield tag="51">
      <labelText>Lower Energy</labelText>
      <size>8</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>aciswin</tableName>
	<columnName>lower_threshold</columnName>
      </database>
    </textfield>
    
    <textfield tag="52">
      <labelText>Energy Range</labelText>
      <size>8</size>
      <database>
        <tableName>aciswin</tableName>
	<columnName>pha_range</columnName>
      </database>
    </textfield>

    <textfield tag="53">
      <labelText>Sample Rate</labelText>
      <size>10</size>
      <database>
        <tableName>aciswin</tableName>
	<columnName>sample</columnName>
      </database>
    </textfield>

 </GUI>

</formView>

=== harlantc/obscycle/prop/gov/sao/asc/obsed/data/tooNewView.xml
<?xml version="1.0" encoding="us-ascii"?>

<!DOCTYPE formView SYSTEM "formView.dtd">

<formView>

  <title>New TOO</title>

  <info>
    <supportsNew></supportsNew>
  </info>

  <key>
    <tableName>too</tableName>
    <columnName>tooid</columnName>
  </key>

  <navigation>
    <display>
      <name>TOO Identifier</name>
      <tableName>too</tableName>
      <columnName>tooid</columnName>
    </display>
  </navigation>

  <GUI>
    <label tag="11">
      <labelText>TOO New Record:</labelText>
      <row>
        <number>0</number>
      </row>
      <column>
        <number>0</number>
      </column>
    </label>

    <combobox tag="20" >
      <labelText>Type</labelText>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>too</tableName>
	<columnName>type</columnName>
      </database>
    </combobox>

    <textfield tag="21">
      <labelText>Response Start</labelText>
      <size>6</size>
      <database>
        <tableName>too</tableName>
	<columnName>start</columnName>
      </database>
    </textfield>

    <textfield tag="22">
      <labelText>Response Stop</labelText>
      <size>6</size>
      <database>
        <tableName>too</tableName>
	<columnName>stop</columnName>
      </database>
    </textfield>

    <textfield tag="23">
      <labelText>Nbr. Followups</labelText>
      <size>6</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>too</tableName>
	<columnName>followup</columnName>
      </database>
    </textfield>

    <textfield tag="33">
      <labelText>Alternate Group</labelText>
      <size>30</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
        <width>2</width>
      </column>
      <database>
        <tableName>too</tableName>
        <columnName>alt_group_name</columnName>
      </database>
    </textfield>

    <textfield tag="34">
      <labelText>Approved Triggers</labelText>
      <size>6</size>
      <column>
        <number>4</number>
      </column>
      <database>
        <tableName>too</tableName>
        <columnName>alt_approved_cnt</columnName>
      </database>
    </textfield>

    <textarea tag="31">
      <anchor>CENTER</anchor>
      <labelText>Trigger Criteria</labelText>
      <size>66</size>
      <row>
        <number>+</number>
        <height>4</height>
      </row>
      <column>
        <number>0</number>
        <width>></width>
      </column>
      <database>
        <tableName>too</tableName>
        <columnName>trig</columnName>
      </database>
    </textarea>

    <textarea tag="41">
      <anchor>CENTER</anchor>
      <labelText>Followup Instructions</labelText>
      <size>66</size>
      <row>
        <number>+</number>
        <height>8</height>
      </row>
      <column>
        <number>0</number>
        <width>></width>
      </column>
      <database>
        <tableName>too</tableName>
        <columnName>remarks</columnName>
      </database>
     </textarea>

 </GUI>

</formView>

=== harlantc/obscycle/prop/gov/sao/asc/obsed/data/acisparamFormView.xml
<?xml version="1.0" encoding="us-ascii"?>

<!DOCTYPE formView SYSTEM "formView.dtd">

<formView>

  <title>ACIS Form</title>

  <info>
    <supportsNew>clone null noDelete</supportsNew>
  </info>

  <key>
    <tableName>acisparam</tableName>
    <columnName>acisid</columnName>
  </key>

  <navigation>
    <display>
      <name>ACIS Identifier</name>
      <tableName>acisparam</tableName>
      <columnName>acisid</columnName>
    </display>
  </navigation>

  <GUI>

    <label tag="11">
      <labelText>ACIS</labelText>
      <row>
        <number>0</number>
      </row>
      <column>
        <number>0</number>
      </column>
    </label>

    <combobox tag="31">
      <labelText>Exposure Mode</labelText>
      <size>8</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>acisparam</tableName>
	<columnName>exp_mode</columnName>
      </database>
    </combobox>

    <combobox tag="32">
      <labelText>BEP Pack</labelText>
      <size>8</size>
      <database>
        <tableName>acisparam</tableName>
	<columnName>bep_pack</columnName>
      </database>
    </combobox>

    <triplebox tag="33">
      <labelText>Most Efficient</labelText>
      <database>
        <tableName>acisparam</tableName>
	<columnName>most_efficient</columnName>
      </database>
    </triplebox>

    <textfield tag="34">
      <labelText>Frame Time</labelText>
      <size>5</size>
      <database>
        <tableName>acisparam</tableName>
	<columnName>frame_time</columnName>
      </database>
    </textfield>


    <textfield tag="41">
      <labelText>Dropped Chip Count</labelText>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>acisparam</tableName>
	<columnName>dropped_chip_count</columnName>
      </database>
    </textfield>

    <combobox tag="42" none="false">
      <labelText>I0</labelText>
      <database>
        <tableName>acisparam</tableName>
	<columnName>ccdi0_on</columnName>
      </database>
    </combobox>

    <combobox tag="43" none="false">
      <labelText>I1</labelText>
      <database>
        <tableName>acisparam</tableName>
	<columnName>ccdi1_on</columnName>
      </database>
    </combobox>


    <combobox tag="52" none="false">
      <labelText>I2</labelText>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>2</number>
      </column>
      <database>
        <tableName>acisparam</tableName>
	<columnName>ccdi2_on</columnName>
      </database>
    </combobox>

    <combobox tag="53" none="false">
      <labelText>I3</labelText>
      <database>
        <tableName>acisparam</tableName>
	<columnName>ccdi3_on</columnName>
      </database>
    </combobox>

    <combobox tag="61" none="false">
      <labelText>S0</labelText>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>acisparam</tableName>
	<columnName>ccds0_on</columnName>
      </database>
    </combobox>

    <combobox tag="62" none="false">
      <labelText>S1</labelText>
      <row>
        <number>.</number>
      </row>
      <column>
        <number>.</number>
      </column>
      <database>
        <tableName>acisparam</tableName>
	<columnName>ccds1_on</columnName>
      </database>
    </combobox>

    <combobox tag="63" none="false">
      <labelText>S2</labelText>
      <row>
        <number>.</number>
      </row>
      <column>
        <number>.</number>
      </column>
      <database>
        <tableName>acisparam</tableName>
	<columnName>ccds2_on</columnName>
      </database>
    </combobox>

    <combobox tag="71" none="false">
      <labelText>S3</labelText>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>acisparam</tableName>
	<columnName>ccds3_on</columnName>
      </database>
    </combobox>

    <combobox tag="72" none="false">
      <labelText>S4</labelText>
      <row>
        <number>.</number>
      </row>
      <column>
        <number>.</number>
      </column>
      <database>
        <tableName>acisparam</tableName>
	<columnName>ccds4_on</columnName>
      </database>
    </combobox>

    <combobox tag="73" none="false">
      <labelText>S5</labelText>
      <row>
        <number>.</number>
      </row>
      <column>
        <number>.</number>
      </column>
      <database>
        <tableName>acisparam</tableName>
	<columnName>ccds5_on</columnName>
      </database>
    </combobox>

    <combobox tag="81">
      <labelText>Subarray Type</labelText>
      <size>7</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>acisparam</tableName>
	<columnName>subarray</columnName>
      </database>
    </combobox>

    <textfield tag="82">
      <labelText>SA Start Row</labelText>
      <size>4</size>
      <database>
        <tableName>acisparam</tableName>
	<columnName>subarray_start_row</columnName>
      </database>
    </textfield>

    <textfield tag="83">
      <labelText>SA #Rows</labelText>
      <size>5</size>
      <database>
        <tableName>acisparam</tableName>
	<columnName>subarray_row_count</columnName>
      </database>
    </textfield>

    <triplebox tag="91">
      <labelText>Duty Cycle</labelText>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>acisparam</tableName>
	<columnName>duty_cycle</columnName>
      </database>
    </triplebox>

    <textfield tag="92">
      <labelText>Number</labelText>
      <size>10</size>
      <database>
        <tableName>acisparam</tableName>
	<columnName>secondary_exp_count</columnName>
      </database>
    </textfield>

    <textfield tag="93">
      <labelText>Tprimary</labelText>
      <size>10</size>
      <database>
        <tableName>acisparam</tableName>
	<columnName>primary_exp_time</columnName>
      </database>
    </textfield>

    <textfield tag="94">
      <labelText>Tsecondary</labelText>
      <size>10</size>
      <database>
        <tableName>acisparam</tableName>
	<columnName>secondary_exp_time</columnName>
      </database>
    </textfield>

    <triplebox tag="101">
      <labelText>Onchip Sum</labelText>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>acisparam</tableName>
	<columnName>onchip_sum</columnName>
      </database>
    </triplebox>

    <textfield tag="102">
      <labelText>Rows</labelText>
      <size>5</size>
      <database>
        <tableName>acisparam</tableName>
	<columnName>onchip_row_count</columnName>
      </database>
    </textfield>

    <textfield tag="103">
      <labelText>Columns</labelText>
      <size>5</size>
      <database>
        <tableName>acisparam</tableName>
	<columnName>onchip_column_count</columnName>
      </database>
    </textfield>

    <triplebox tag="111">
      <labelText>Event Filter</labelText>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>acisparam</tableName>
	<columnName>eventfilter</columnName>
      </database>
    </triplebox>

    <textfield tag="112">
      <labelText>Lower</labelText>
      <size>10</size>
      <database>
        <tableName>acisparam</tableName>
	<columnName>eventfilter_lower</columnName>
      </database>
    </textfield>

    <textfield tag="113">
      <labelText>Range</labelText>
      <size>10</size>
      <database>
        <tableName>acisparam</tableName>
	<columnName>eventfilter_higher</columnName>
      </database>
    </textfield>

    <combobox tag="511">
      <labelText>Multiple Spectral Lines </labelText>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>acisparam</tableName>
	<columnName>multiple_spectral_lines</columnName>
      </database>
    </combobox>

    <textfield tag="512">
      <labelText>Spectra Max Count</labelText>
      <size>10</size>
      <database>
        <tableName>acisparam</tableName>
	<columnName>spectra_max_count</columnName>
      </database>
    </textfield>

 </GUI>

</formView>

=== harlantc/obscycle/prop/gov/sao/asc/obsed/data/aciswinNewView.xml
<?xml version="1.0" encoding="us-ascii"?>

<!DOCTYPE formView SYSTEM "formView.dtd">

<formView>

  <title>New ACISWin</title>

  <info>
    <supportsNew></supportsNew>
  </info>

  <key>
    <tableName>aciswin</tableName>
    <columnName>aciswin_id</columnName>
  </key>

  <navigation>
    <display>
      <name>ACISWIN Identifier</name>
      <tableName>aciswin</tableName>
      <columnName>aciswin_id</columnName>
    </display>
  </navigation>

  <GUI>
    <label tag="11">
      <labelText>ACISWin</labelText>
      <row>
        <number>0</number>
      </row>
      <column>
        <number>0</number>
      </column>
    </label>

    <keycombobox tag="11" >
      <labelText>Obs ID</labelText>
      <size>6</size>
      <database>
        <tableName>aciswin</tableName>
        <columnName>obsid</columnName>
	<queryString>SELECT distinct target.obsid FROM target,acisparam WHERE NOT EXISTS (SELECT 1 FROM locked WHERE locked.obsid = target.obsid) AND target.acisid is NOT NULL AND target.acisid = acisparam.acisid and acisparam.spwindow='Y' ORDER BY target.obsid</queryString>
      </database>
      <keyinfo>
        <keyTableName>target</keyTableName>
        <keyColumnName>obsid</keyColumnName>
      </keyinfo>
    </keycombobox>

    <textfield tag="120" >
      <labelText>Order</labelText>
      <size>2</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>aciswin</tableName>
        <columnName>ordr</columnName>
      </database>
    </textfield>

    
    <combobox tag="121" >
      <labelText>Chip</labelText>
      <size>6</size>
      <database>
        <tableName>aciswin</tableName>
        <columnName>chip</columnName>
      </database>
    </combobox>

    <combobox tag="122" >
      <labelText>Include Flag</labelText>
      <database>
        <tableName>aciswin</tableName>
        <columnName>include_flag</columnName>
      </database>
    </combobox>


    <textfield tag="131">
      <labelText>Start Row</labelText>
      <size>5</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>aciswin</tableName>
	<columnName>start_row</columnName>
      </database>
    </textfield>

    <textfield tag="132">
      <labelText>Start Column</labelText>
      <size>5</size>
      <database>
        <tableName>aciswin</tableName>
	<columnName>start_column</columnName>
      </database>
    </textfield>

    <textfield tag="141">
      <labelText>Height</labelText>
      <size>10</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>aciswin</tableName>
	<columnName>height</columnName>
      </database>
    </textfield>

    <textfield tag="142">
      <labelText>Width</labelText>
      <size>10</size>
      <database>
        <tableName>aciswin</tableName>
	<columnName>width</columnName>
      </database>
    </textfield>

    <textfield tag="151">
      <labelText>Lower Energy</labelText>
      <size>8</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>aciswin</tableName>
	<columnName>lower_threshold</columnName>
      </database>
    </textfield>
    
    <textfield tag="152">
      <labelText>Energy Range</labelText>
      <size>8</size>
      <database>
        <tableName>aciswin</tableName>
	<columnName>pha_range</columnName>
      </database>
    </textfield>

    <textfield tag="153">
      <labelText>Sample Rate</labelText>
      <size>10</size>
      <database>
        <tableName>aciswin</tableName>
	<columnName>sample</columnName>
      </database>
    </textfield>


 </GUI>

</formView>

=== harlantc/obscycle/prop/gov/sao/asc/obsed/data/timereqNewView.xml
<?xml version="1.0" encoding="us-ascii"?>

<!DOCTYPE formView SYSTEM "formView.dtd">

<formView>

  <title>New TIMEREQ Form</title>

  <info>
    <supportsNew></supportsNew>
  </info>

  <key>
    <tableName>timereq</tableName>
    <columnName>timereq_id</columnName>
  </key>

  <navigation>
    <display>
      <name>TIMEREQ Identifier</name>
      <tableName>timereq</tableName>
      <columnName>timereq_id</columnName>
    </display>
  </navigation>

  <GUI>
    <label tag="11">
      <labelText>TIMEREQ</labelText>
      <row>
        <number>0</number>
      </row>
      <column>
        <number>0</number>
      </column>
    </label>


    <textfield tag="13">
      <labelText>Obs Id</labelText>
      <size>6</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>timereq</tableName>
        <columnName>obsid</columnName>
      </database>
    </textfield>

   <textfield tag="13">
      <labelText>Order</labelText>
      <size>6</size>
      <database>
        <tableName>timereq</tableName>
        <columnName>ordr</columnName>
      </database>
    </textfield>
    
   <combobox tag="21" >
      <labelText>Window Constraint</labelText>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <size>1</size>
      <database>
        <tableName>timereq</tableName>
        <columnName>window_constraint</columnName>
      </database>
    </combobox>

    <timestampbutton tag="22">
      <labelText>Window Start</labelText>
      <size>22</size>
      <database>
        <tableName>timereq</tableName>
        <columnName>tstart</columnName>
      </database>
    </timestampbutton>

    <timestampbutton tag="23">
      <labelText>Window Stop</labelText>
      <size>22</size>
      <database>
        <tableName>timereq</tableName>
        <columnName>tstop</columnName>
      </database>
    </timestampbutton>


 </GUI>

</formView>
