=== harlantc/obscycle/prop/gov/sao/asc/obsed/data/formView.dtd
<?xml version="1.0" encoding="us-ascii"?>

<!ELEMENT formView (title,info,key,navigation,GUI)>

<!ELEMENT title (#PCDATA)>
<!ELEMENT info (supportsNew)>
<!ELEMENT supportsNew (#PCDATA)>
<!ELEMENT key (tableName, columnName)>
<!ELEMENT tableName (#PCDATA)>
<!ELEMENT columnName (#PCDATA)>

<!ELEMENT navigation (display+)>
<!ELEMENT display (name, tableName, columnName)>
<!ELEMENT name (#PCDATA)>

<!ELEMENT GUI (textfield | combobox | keycombobox | triplebox | obsidcombobox | obsidbutton | seqnbrbutton | separator | label | textarea | timestampbutton)+>
<!ELEMENT textfield (labelText, size?, row?, column?, database, anchor? )>
<!ATTLIST textfield tag ID #REQUIRED>
<!ELEMENT labelText (#PCDATA)>
<!ELEMENT size (#PCDATA)>
<!ELEMENT row (number, height)>
<!ELEMENT number (#PCDATA)>
<!ELEMENT height (#PCDATA)>
<!ELEMENT column (number, width)>
<!ELEMENT width (#PCDATA)>
<!ELEMENT database (tableName, columnName, joinTableName?, joinColumnName?, queryString?)>
<!ELEMENT keyinfo (keyTableName, keyColumnName)>
<!ELEMENT combobox (labelText, size?, row?, column?, database, null?, anchor?)>
<!ATTLIST combobox tag ID #REQUIRED none (true | false) "true" new (true | false) "false">
<!ELEMENT keycombobox (labelText, size?, row?, column?, database, keyinfo, null?, anchor?)>
<!ATTLIST keycombobox tag ID #REQUIRED new (true | false) "false" none (true | false) "true">
<!ELEMENT triplebox (labelText, row?, column?, database, null?, anchor?)>
<!ATTLIST triplebox tag ID #REQUIRED>
<!ELEMENT obsidcombobox (labelText, row?, column?, database, null?, anchor?)>
<!ATTLIST obsidcombobox tag ID #REQUIRED>
<!ELEMENT obsidbutton (labelText, row?, column?, database, anchor? )>
<!ATTLIST obsidbutton tag ID #REQUIRED>
<!ELEMENT seqnbrbutton (labelText, row?, column?, database, anchor? )>
<!ATTLIST seqnbrbutton tag ID #REQUIRED>
<!ELEMENT separator EMPTY>
<!ELEMENT label (labelText, anchor?, row?, column?)>
<!ELEMENT null (representation, value?)>
<!ELEMENT representation (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT anchor (#PCDATA)>
<!ELEMENT textarea (labelText, size?, row?, column?, database, anchor?)>
<!ATTLIST textarea tag ID #REQUIRED>
<!ELEMENT timestampbutton (labelText, row?, column?, database, anchor? )>
<!ATTLIST timestampbutton tag ID #REQUIRED>

<!ELEMENT constraintList (constraint+)>
<!ELEMENT constraint (entry | grating | firstOrderCountRate | yOffset | zOffset | radial | instrument | type | ra | dec | ssObject | angle| tolerance | startTime | stopTime | photometry | visualMag)>
<!ATTLIST constraint type ID #REQUIRED>
<!ELEMENT entry (#PCDATA)>
<!ELEMENT grating (#PCDATA)>
<!ELEMENT firstOrderCountRate (#PCDATA)>
<!ELEMENT yOffset (#PCDATA)>
<!ELEMENT zOffset (#PCDATA)>
<!ELEMENT radial (#PCDATA)>
<!ELEMENT instrument (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT ra (#PCDATA)>
<!ELEMENT dec (#PCDATA)>
<!ELEMENT ssObject (#PCDATA)>
<!ELEMENT angle (#PCDATA)>
<!ELEMENT tolerance (#PCDATA)>
<!ELEMENT startTime (#PCDATA)>
<!ELEMENT stopTime (#PCDATA)>
<!ELEMENT photometry (#PCDATA)>
<!ELEMENT visualMag (#PCDATA)>

=== harlantc/obscycle/prop/gov/sao/asc/obsed/data/phasereqNewView.xml
<?xml version="1.0" encoding="us-ascii"?>

<!DOCTYPE formView SYSTEM "formView.dtd">

<formView>
  <title>New Phasreq</title>

  <info>
    <supportsNew>true</supportsNew>
  </info>

  <key>
    <tableName>phasereq</tableName>
    <columnName>obsid</columnName>
  </key>

  <navigation>
    <display>
      <name>Observation ID</name>
      <tableName>phasereq</tableName>
      <columnName>obsid</columnName>
    </display>
  </navigation>

  <GUI>
    <obsidcombobox tag="11">
      <labelText>Obs ID</labelText>
      <size>6</size>
      <row>
        <number>0</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>phasereq</tableName>
        <columnName>obsid</columnName>
	<queryString>SELECT target.obsid FROM target WHERE NOT EXISTS (SELECT 1 FROM locked WHERE locked.obsid = target.obsid) AND NOT EXISTS (SELECT 1 FROM phasereq WHERE phasereq.obsid = target.obsid)</queryString>
      </database>
    </obsidcombobox>
    
    <textfield tag="21">
      <labelText>Phase Period</labelText>
      <size>8</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>phasereq</tableName>
        <columnName>phase_period</columnName>
      </database>
    </textfield>
    
    <textfield tag="22">
      <labelText>Phase Epoch</labelText>
      <size>8</size>
      <database>
        <tableName>phasereq</tableName>
        <columnName>phase_epoch</columnName>
      </database>
    </textfield>

    <textfield tag="31">
      <labelText>Phase Start</labelText>
      <size>8</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>phasereq</tableName>
        <columnName>phase_start</columnName>
      </database>
    </textfield>
    
    <textfield tag="32">
      <labelText>Phase End</labelText>
      <size>8</size>
      <database>
        <tableName>phasereq</tableName>
        <columnName>phase_end</columnName>
      </database>
    </textfield>

    <textfield tag="41">
      <labelText>Phase Start Margin</labelText>
      <size>8</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>phasereq</tableName>
        <columnName>phase_start_margin</columnName>
      </database>
    </textfield>
    
    <textfield tag="42">
      <labelText>Phase End</labelText>
      <size>8</size>
      <database>
        <tableName>phasereq</tableName>
        <columnName>phase_end_margin</columnName>
      </database>
    </textfield>

    <combobox tag="51" none="false">
      <labelText>Phase Unique</labelText>
      <size>1</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>phasereq</tableName>
        <columnName>phase_unique</columnName>
      </database>
    </combobox>

  </GUI>
</formView>

=== harlantc/obscycle/prop/gov/sao/asc/obsed/data/ditherFormView.xml
<?xml version="1.0" encoding="us-ascii"?>

<!DOCTYPE formView SYSTEM "formView.dtd">

<formView>

  <title>Dither Form</title>

  <info>
  <supportsNew>clone null</supportsNew>
  </info>

  <key>
    <tableName>dither</tableName>
    <columnName>obsid</columnName>
  </key>

  <navigation>
    <display>
      <name>Observation ID</name>
      <tableName>dither</tableName>
      <columnName>obsid</columnName>
    </display>
  </navigation>

  <GUI>
    <label tag="11">
      <labelText>Dither</labelText>
      <row>
        <number>0</number>
      </row>
      <column>
        <number>0</number>
      </column>
    </label>

   <textfield tag="21">
      <labelText>Y Amplitude</labelText>
      <size>8</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>dither</tableName>
	<columnName>y_amp</columnName>
      </database>
    </textfield>

   <textfield tag="22">
      <labelText>Y Frequency</labelText>
      <size>8</size>
      <database>
        <tableName>dither</tableName>
	<columnName>y_freq</columnName>
      </database>
    </textfield>

   <textfield tag="23">
      <labelText>Y Phase</labelText>
      <size>8</size>
      <database>
        <tableName>dither</tableName>
	<columnName>y_phase</columnName>
      </database>
    </textfield>

   <textfield tag="31">
      <labelText>Z Amplitude</labelText>
      <size>8</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>dither</tableName>
	<columnName>z_amp</columnName>
      </database>
    </textfield>

   <textfield tag="32">
      <labelText>Z Frequency</labelText>
      <size>8</size>
      <database>
        <tableName>dither</tableName>
	<columnName>z_freq</columnName>
      </database>
    </textfield>

   <textfield tag="33">
      <labelText>Z Phase</labelText>
      <size>8</size>
      <database>
        <tableName>dither</tableName>
	<columnName>z_phase</columnName>
      </database>
    </textfield>

 </GUI>

</formView>

=== harlantc/obscycle/prop/gov/sao/asc/obsed/data/phasereqFormView.xml
<?xml version="1.0" encoding="us-ascii"?>

<!DOCTYPE formView SYSTEM "formView.dtd">

<formView>

  <title>Phase Req Form</title>

  <info>
    <supportsNew>clone null</supportsNew>
  </info>

  <key>
    <tableName>phasereq</tableName>
    <columnName>obsid</columnName>
  </key>

  <navigation>
    <display>
      <name>Observation ID</name>
      <tableName>phasereq</tableName>
      <columnName>obsid</columnName>
    </display>
  </navigation>

  <GUI>
    <label tag="11">
      <labelText>Phase Req</labelText>
      <row>
        <number>0</number>
      </row>
      <column>
        <number>0</number>
      </column>
    </label>

   <textfield tag="21">
      <labelText>Phase Period</labelText>
      <size>8</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>phasereq</tableName>
	<columnName>phase_period</columnName>
      </database>
    </textfield>

   <textfield tag="22">
      <labelText>Phase Epoch</labelText>
      <size>8</size>
      <database>
        <tableName>phasereq</tableName>
	<columnName>phase_epoch</columnName>
      </database>
    </textfield>

   <textfield tag="31">
      <labelText>Phase Start</labelText>
      <size>8</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>phasereq</tableName>
	<columnName>phase_start</columnName>
      </database>
    </textfield>

   <textfield tag="32">
      <labelText>Phase End</labelText>
      <size>8</size>
      <database>
        <tableName>phasereq</tableName>
	<columnName>phase_end</columnName>
      </database>
    </textfield>

   <textfield tag="41">
      <labelText>Phase Start Margin</labelText>
      <size>8</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>phasereq</tableName>
	<columnName>phase_start_margin</columnName>
      </database>
    </textfield>

   <textfield tag="42">
      <labelText>Phase End Margin</labelText>
      <size>8</size>
      <database>
        <tableName>phasereq</tableName>
	<columnName>phase_end_margin</columnName>
      </database>
    </textfield>

    <combobox tag="51" none="false">
      <labelText>Phase Unique</labelText>
      <size>1</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>phasereq</tableName>
        <columnName>phase_unique</columnName>
      </database>
    </combobox>

  </GUI>
</formView>

=== harlantc/obscycle/prop/gov/sao/asc/obsed/data/rollreqFormView.xml
<?xml version="1.0" encoding="us-ascii"?>

<!DOCTYPE formView SYSTEM "formView.dtd">

<formView>

  <title>ROLLREQ Form</title>

  <info>
    <supportsNew>clone null</supportsNew>
  </info>

  <key>
    <tableName>rollreq</tableName>
    <columnName>rollreq_id</columnName>
  </key>

  <navigation>
    <display>
      <name>ROLLREQ Identifier</name>
      <tableName>rollreq</tableName>
      <columnName>rollreq_id</columnName>
    </display>
    <display>
      <name>ObsId+Order</name>
      <tableName>rollreq</tableName>
      <columnName>(convert(char(8),obsid)+convert(char(4),ordr))</columnName>
    </display>
  </navigation>

  <GUI>
    <label tag="11">
      <labelText>ROLLREQ</labelText>
      <row>
        <number>0</number>
      </row>
      <column>
        <number>0</number>
      </column>
    </label>

    <textfield tag="12">
      <labelText>Id</labelText>
      <size>6</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>rollreq</tableName>
        <columnName>rollreq_id</columnName>
      </database>
    </textfield>


    <textfield tag="13">
      <labelText>Obs Id</labelText>
      <size>6</size>
      <database>
        <tableName>rollreq</tableName>
        <columnName>obsid</columnName>
      </database>
    </textfield>

    <textfield tag="14">
      <labelText>Order</labelText>
      <size>2</size>
      <database>
        <tableName>rollreq</tableName>
        <columnName>ordr</columnName>
      </database>
    </textfield>
    
   <combobox tag="21" none="false">
      <labelText>Roll Constraint</labelText>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <size>1</size>
      <database>
        <tableName>rollreq</tableName>
        <columnName>roll_constraint</columnName>
      </database>
    </combobox>

    <combobox tag="22">
      <labelText>Roll 180?</labelText>
      <database>
        <tableName>rollreq</tableName>
        <columnName>roll_180</columnName>
      </database>
    </combobox>

    <textfield tag="31">
      <labelText>Roll Angle</labelText>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <size>6</size>
      <database>
        <tableName>rollreq</tableName>
        <columnName>roll</columnName>
      </database>
    </textfield>
   
    <textfield tag="32">
      <labelText>Roll Tolerance</labelText>
      <size>6</size>
      <database>
        <tableName>rollreq</tableName>
        <columnName>roll_tolerance</columnName>
      </database>
    </textfield>


 </GUI>

</formView>

=== harlantc/obscycle/prop/gov/sao/asc/obsed/data/simNewView.xml
<?xml version="1.0" encoding="us-ascii"?>

<!DOCTYPE formView SYSTEM "formView.dtd">

<formView>
  <title>New SIM</title>

  <info>
    <supportsNew>true</supportsNew>
  </info>

  <key>
    <tableName>sim</tableName>
    <columnName>obsid</columnName>
  </key>

  <navigation>
    <display>
      <name>Observation ID</name>
      <tableName>sim</tableName>
      <columnName>obsid</columnName>
    </display>
  </navigation>

  <GUI>
    <obsidcombobox tag="11">
      <labelText>Obs ID</labelText>
      <size>6</size>
      <row>
        <number>0</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>sim</tableName>
        <columnName>obsid</columnName>
	<queryString>SELECT target.obsid FROM target WHERE NOT EXISTS (SELECT 1 FROM locked WHERE locked.obsid = target.obsid) AND NOT EXISTS (SELECT 1 FROM sim WHERE sim.obsid = target.obsid)</queryString>
      </database>
    </obsidcombobox>
    
    <textfield tag="12">
      <labelText>Trans Offset</labelText>
      <size>8</size>
      <database>
        <tableName>sim</tableName>
        <columnName>trans_offset</columnName>
      </database>
    </textfield>
    
    <textfield tag="21">
      <labelText>Focus Offset</labelText>
      <size>8</size>
      <database>
        <tableName>sim</tableName>
        <columnName>focus_offset</columnName>
      </database>
    </textfield>

  </GUI>

</formView>

=== harlantc/obscycle/prop/gov/sao/asc/obsed/data/observing_cycleNewView.xml
<?xml version="1.0" encoding="us-ascii"?>

<!DOCTYPE formView SYSTEM "formView.dtd">

<formView>

  <title>New Observing Cycle</title>

  <info>
    <supportsNew></supportsNew>
  </info>

  <key>
    <tableName>observing_cycle</tableName>
    <columnName>ao_id</columnName>
  </key>

  <navigation>
    <display>
      <name>Observing Cycle Identifier</name>
      <tableName>observing_cycle</tableName>
      <columnName>ao_id</columnName>
    </display>
    <display>
      <name>Cycle</name>
      <tableName>observing_cycle</tableName>
      <columnName>ao_str</columnName>
    </display>

  </navigation>

  <GUI>
    <label tag="11">
      <labelText>Observing Cycle</labelText>
      <row>
        <number>0</number>
      </row>
      <column>
        <number>0</number>
      </column>
    </label>


    <textfield tag="13">
      <labelText>Cycle</labelText>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <size>6</size>
      <database>
        <tableName>observing_cycle</tableName>
        <columnName>ao_str</columnName>
      </database>
    </textfield>

   <timestampbutton tag="22">
      <labelText>Start Date</labelText>
      <size>8</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>observing_cycle</tableName>
        <columnName>ao_start</columnName>
      </database>
    </timestampbutton>

   <timestampbutton tag="22">
      <labelText>End Date</labelText>
      <size>8</size>
      <database>
        <tableName>observing_cycle</tableName>
        <columnName>ao_end</columnName>
      </database>
    </timestampbutton>

 </GUI>

</formView>

=== harlantc/obscycle/prop/gov/sao/asc/obsed/data/mt_ephemFormView.xml
<?xml version="1.0" encoding="us-ascii"?>

<!DOCTYPE formView SYSTEM "formView.dtd">

<formView>

  <title>Orbit Form</title>

  <info>
    <supportsNew>clone null</supportsNew>
  </info>

  <key>
    <tableName>mt_ephem</tableName>
    <columnName>obsid</columnName>
  </key>

  <navigation>
    <display>
      <name>Observation ID</name>
      <tableName>mt_ephem</tableName>
      <columnName>obsid</columnName>
    </display>
  </navigation>

  <GUI>
    <textfield tag="11">
      <labelText>ObsID</labelText>
      <size>8</size>
      <database>
        <tableName>mt_ephem</tableName>
        <columnName>obsid</columnName>
      </database>
    </textfield>
    
    <textfield tag="21">
      <labelText>Epoch</labelText>
      <size>8</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>mt_ephem</tableName>
        <columnName>epoch</columnName>
      </database>
    </textfield>
    
    <textfield tag="22">
      <labelText>Semi-major Axis</labelText>
      <size>8</size>
      <database>
        <tableName>mt_ephem</tableName>
        <columnName>axis</columnName>
      </database>
    </textfield>
    
    <textfield tag="23">
      <labelText>Eccentricity</labelText>
      <size>8</size>
      <database>
        <tableName>mt_ephem</tableName>
        <columnName>eccentricity</columnName>
      </database>
    </textfield>

    <textfield tag="31">
      <labelText>Inclination</labelText>
      <size>8</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>mt_ephem</tableName>
        <columnName>inclination</columnName>
      </database>
    </textfield>
    
    <textfield tag="32">
      <labelText>RA of Ascending Node</labelText>
      <size>8</size>
      <database>
        <tableName>mt_ephem</tableName>
        <columnName>raan</columnName>
      </database>
    </textfield>
    
    <textfield tag="33">
      <labelText>Arg of Periastron</labelText>
      <size>8</size>
      <database>
        <tableName>mt_ephem</tableName>
        <columnName>aop</columnName>
      </database>
    </textfield>
    
    <textfield tag="41">
      <labelText>Mean Anomaly at Epoch</labelText>
      <size>8</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>mt_ephem</tableName>
        <columnName>ma</columnName>
      </database>
    </textfield>
  </GUI>

</formView>

=== harlantc/obscycle/prop/gov/sao/asc/obsed/data/mpFormView.xml
<?xml version="1.0" encoding="us-ascii"?>

<!DOCTYPE formView SYSTEM "formView.dtd">

<formView>

  <title>MP Form</title>

  <info>
    <supportsNew>nil</supportsNew>
  </info>

  <key>
    <tableName>mp</tableName>
    <columnName>obsid</columnName>
  </key>

  <navigation>
    <display>
      <name>Observation ID</name>
      <tableName>mp</tableName>
      <columnName>obsid</columnName>
    </display>
  </navigation>

  <GUI>
    <label tag="11">
      <labelText>Mission Planning</labelText>
      <row>
        <number>0</number>
      </row>
      <column>
        <number>0</number>
      </column>
    </label>

   <textfield tag="21">
      <labelText>Counter</labelText>
      <size>8</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>mp</tableName>
	<columnName>counter</columnName>
      </database>
    </textfield>

   <textfield tag="22">
      <labelText>Sequence Number</labelText>
      <size>8</size>
      <database>
        <tableName>mp</tableName>
	<columnName>seq_nbr</columnName>
      </database>
    </textfield>

   <textfield tag="31">
      <labelText>Priority</labelText>
      <size>8</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>mp</tableName>
	<columnName>mp_priority</columnName>
      </database>
    </textfield>

   <textfield tag="32">
      <labelText>Roll</labelText>
      <size>8</size>
      <database>
        <tableName>mp</tableName>
	<columnName>mp_roll</columnName>
      </database>
    </textfield>

   <textfield tag="33">
      <labelText>Roll Tolerance</labelText>
      <size>8</size>
      <database>
        <tableName>mp</tableName>
	<columnName>mp_roll_tolerance</columnName>
      </database>
    </textfield>

   <textfield tag="41">
      <labelText>Star Fidlight File</labelText>
      <size>8</size>
      <row>
        <number>+</number>
      </row>
      <column>
        <number>0</number>
      </column>
      <database>
        <tableName>mp</tableName>
	<columnName>star_fidlight_file</columnName>
      </database>
    </textfield>

   <timestampbutton tag="42">
      <labelText>LT Plan</labelText>
      <size>8</size>
      <database>
        <tableName>mp</tableName>
	<columnName>lt_plan</columnName>
      </database>
    </timestampbutton>

   <textfield tag="43">
      <labelText>Duration</labelText>
      <size>8</size>
      <database>
        <tableName>mp</tableName>
	<columnName>duration</columnName>
      </database>
    </textfield>

 </GUI>

</formView>
