=== harlantc/obscycle/prop/gov/sao/asc/obsed/data/table.dtd
<?xml version="1.0" encoding="us-ascii"?>

<!ELEMENT table (column+)>
<!ATTLIST table name ID #REQUIRED>
<!ATTLIST table key CDATA #REQUIRED>

<!ELEMENT column (type, tooltip, foreignKeyTable*, number?, choices?, constraint*)>
<!ATTLIST column name ID #REQUIRED>
<!ELEMENT type (#PCDATA)>
<!ELEMENT tooltip (#PCDATA)>
<!ELEMENT foreignKeyTable (#PCDATA)>
<!ELEMENT number (maximum?, minimum?, format?)>
<!ELEMENT maximum (#PCDATA)>
<!ELEMENT minimum (#PCDATA)>
<!ELEMENT format (#PCDATA)>
<!ELEMENT choices (item)+>
<!ELEMENT item (#PCDATA)>

<!ELEMENT constraint (#PCDATA)>

=== harlantc/obscycle/prop/gov/sao/asc/obsed/data/phasereqTable.xml
<?xml version="1.0" encoding="us-ascii"?>

<!DOCTYPE table SYSTEM "table.dtd">

<table name="phasereq" key="obsid">
  <column name="obsid">
    <type>INTEGER</type>
    <tooltip>Observation Identifier</tooltip>
  </column>
  <column name="phase_period">
    <type>DOUBLE</type>
    <tooltip>Phase Period(days)</tooltip>
  </column>
  <column name="phase_epoch">
    <type>DOUBLE</type>
    <tooltip>Phase Epoch(MJD)</tooltip>
    <number>
      <minimum>46066.0</minimum>
    </number>
  </column>
  <column name="phase_start">
    <type>DOUBLE</type>
    <tooltip>Minimum Orbital Phase</tooltip>
    <number>
      <maximum>1.0</maximum>
      <minimum>0.0</minimum>
    </number>
  </column>
  <column name="phase_end">
    <type>DOUBLE</type>
    <tooltip>Maximum Orbital Phase</tooltip>
    <number>
      <maximum>1.0</maximum>
      <minimum>0.0</minimum>
    </number>
  </column>
  <column name="phase_start_margin">
    <type>DOUBLE</type>
    <tooltip>Error margin on minimum orbital phase</tooltip>
    <number>
      <maximum>1.0</maximum>
      <minimum>0.0</minimum>
    </number>
  </column>
  <column name="phase_end_margin">
    <type>DOUBLE</type>
    <tooltip>Error margin on maximum orbital phase</tooltip>
    <number>
      <maximum>1.0</maximum>
      <minimum>0.0</minimum>
    </number>
  </column>
  <column name="phase_unique">
    <type>CHOICE</type> 
    <tooltip>Is the phase unique</tooltip>
    <choices>
      <item>N</item>
      <item>Y</item>
    </choices>
  </column>
</table>

=== harlantc/obscycle/prop/gov/sao/asc/obsed/data/observing_cycleTable.xml
<?xml version="1.0" encoding="us-ascii"?>

<!DOCTYPE table SYSTEM "table.dtd">

<table name="observing_cycle" key="ao_id">
  <column name="ao_id">
    <type>INTEGER</type>
    <tooltip>Database index for observing_cycle table</tooltip>
  </column>
  <column name="ao_str">
    <type>STRING</type>
    <tooltip>Observation Cycle </tooltip>
  </column>
  <column name="ao_start">
    <type>DATE</type>
    <tooltip>Start of observing cycle </tooltip>
  </column>
  <column name="ao_end">
    <type>DATE</type>
    <tooltip>End of observing cycle </tooltip>
  </column>
</table>

=== harlantc/obscycle/prop/gov/sao/asc/obsed/data/aciswinTable.xml
<?xml version="1.0" encoding="us-ascii"?>

<!DOCTYPE table SYSTEM "table.dtd">

<table name="aciswin" key="aciswin_id">
  <column name="aciswin_id">
    <type>INTEGER</type>
    <tooltip>Database index for aciswin table</tooltip>
  </column>
  <column name="obsid">
    <type>INTEGER</type>
    <tooltip>Observation ID</tooltip>
  </column>
  <column name="ordr">
    <type>INTEGER</type>
    <tooltip>Indicates the order within the chip for multiple spatial windows</tooltip>
    <number>
      <maximum>6</maximum>
      <minimum>1</minimum>
    </number>
  </column>
  <column name="chip">
    <type>CHOICE</type>
    <tooltip>Indicates the chip to use for spatial window</tooltip>
    <choices>
      <item>I0</item>
      <item>I1</item>
      <item>I2</item>
      <item>I3</item>
      <item>S0</item>
      <item>S1</item>
      <item>S2</item>
      <item>S3</item>
      <item>S4</item>
      <item>S5</item>
    </choices>
  </column>
  <column name="include_flag">
    <type>CHOICE</type>
    <tooltip>Include (I) or Exclude (E) all of the photons in the defined region</tooltip>
    <choices>
      <item>E</item>
      <item>I</item>
    </choices>
  </column>
  <column name="start_row">
    <type>INTEGER</type>
    <tooltip>Spatial Window Start Row</tooltip>
    <number>
      <maximum>1023</maximum>
      <minimum>1</minimum>
    </number>
  </column>
  <column name="start_column">
    <type>INTEGER</type>
    <tooltip>Spatial Window Start Column</tooltip>
    <number>
      <maximum>1023</maximum>
      <minimum>1</minimum>
    </number>
  </column>
  <column name="width">
    <type>INTEGER</type>
    <tooltip>Spatial Window Width</tooltip>
    <number>
      <maximum>1024</maximum>
      <minimum>1</minimum>
    </number>
  </column>
  <column name="height">
    <type>INTEGER</type>
    <tooltip>Spatial Window Height</tooltip>
    <number>
      <maximum>1024</maximum>
      <minimum>1</minimum>
    </number>
  </column>
  <column name="lower_threshold">
    <type>DOUBLE</type>
    <tooltip>Spatial Window Lower Threshold</tooltip>
    <number>
      <maximum>15.0</maximum>
      <minimum>0.08</minimum>
    </number>
  </column>
  <column name="pha_range">
    <type>DOUBLE</type>
    <tooltip>Spatial Window Energy Range</tooltip>
    <number>
      <maximum>15.0</maximum>
      <minimum>0.1</minimum>
    </number>
  </column>
  <column name="sample">
    <type>INTEGER</type>
    <tooltip>Spatial Window Sampling Rate</tooltip>
    <number>
      <maximum>512</maximum>
      <minimum>0</minimum>
    </number>
  </column>
</table>

=== harlantc/obscycle/prop/gov/sao/asc/obsed/data/anc_targetTable.xml
<?xml version="1.0" encoding="us-ascii"?>

<!DOCTYPE table SYSTEM "table.dtd">

<table name="anc_target" key="targid">
  <column name="targid">
    <type>INTEGER</type>
    <tooltip>Target Identifier in the proposal database</tooltip>
  </column>
  <column name="targ_num">
    <type>INTEGER</type>
    <tooltip>Target Number in the proposal database</tooltip>
  </column>
  <column name="ss_nudge">
    <type>BOOLEAN</type>
    <tooltip>Solar System Nudge Mode flag</tooltip>
  </column>
  <column name="coord_epoch">
    <type>INTEGER</type>
    <tooltip>Coord Epoch</tooltip>
  </column>
</table>

=== harlantc/obscycle/prop/gov/sao/asc/obsed/data/grant_infoTable.xml
<?xml version="1.0" encoding="us-ascii"?>

<!DOCTYPE table SYSTEM "table.dtd">

<table name="grant_info" key="grant_id">
  <column name="grant_id">
    <type>INTEGER</type>
    <tooltip>Database index for grant_info table</tooltip>
  </column>
  <column name="ocat_propid">
    <type>INTEGER</type>
    <tooltip>Associated prop_info table id  </tooltip>
    <foreignKeyTable>prop_info</foreignKeyTable>
  </column>
  <column name="grant_number">
    <type>STRING</type>
    <tooltip>Grant number </tooltip>
  </column>
  <column name="grant_type">
    <type>STRING</type>
    <tooltip>Grant type </tooltip>
  </column>
  <column name="grant_ao">
    <type>STRING</type>
    <tooltip>Grant AO (proposal cycle) </tooltip>
  </column>
  <column name="grantor">
    <type>STRING</type>
    <tooltip>Grantor</tooltip>
  </column>
  <column name="grant_amount">
    <type>DOUBLE</type>
    <tooltip>Grant Amount</tooltip>
  </column>
</table>

=== harlantc/obscycle/prop/gov/sao/asc/obsed/data/grant_recipientTable.xml
<?xml version="1.0" encoding="us-ascii"?>

<!DOCTYPE table SYSTEM "table.dtd">

<table name="grant_recipient" key="id">
  <column name="id">
    <type>INTEGER</type>
    <tooltip>Database index for grant_recipient table</tooltip>
  </column>
  <column name="grant_id">
    <type>INTEGER</type>
    <tooltip>Database index for grant_info table</tooltip>
    <foreignKeyTable>grant_info</foreignKeyTable>
  </column>
  <column name="pers_id">
    <type>INTEGER</type>
    <tooltip>Associated axafusers person id  </tooltip>
    <foreignKeyTable>axafusers..person_short</foreignKeyTable>
  </column>
</table>

=== harlantc/obscycle/prop/gov/sao/asc/obsed/data/rollreqTable.xml
<?xml version="1.0" encoding="us-ascii"?>

<!DOCTYPE table SYSTEM "table.dtd">

<table name="rollreq" key="rollreq_id">
  <column name="rollreq_id">
    <type>INTEGER</type>
    <tooltip>Database index for rollreq table</tooltip>
  </column>
  <column name="obsid">
    <type>INTEGER</type>
    <tooltip>Observation ID</tooltip>
  </column>
  <column name="ordr">
    <type>INTEGER</type>
    <tooltip>Order for rollreq table entry per ObsId</tooltip>
  </column>
  <column name="roll_constraint">
    <type>CHOICE</type>
    <tooltip>Flag indicating roll constraint is required(Y) or  preferred(P)</tooltip>
    <choices>
       <item>Y</item>
       <item>P</item>
    </choices>
  </column>
  <column name="roll_180">
    <type>CHOICE</type>
    <tooltip>Flag indicating roll constraint may be rotated 180 degrees</tooltip>
    <choices>
        <item>Y</item>
        <item>N</item>
    </choices>
  </column>
  <column name="roll">
    <type>DOUBLE</type>
    <tooltip>Roll angle</tooltip>
    <number>
      <maximum>360.0</maximum>
      <minimum>0.0</minimum>
    </number>
  </column>
  <column name="roll_tolerance">
    <type>DOUBLE</type>
    <tooltip>Roll tolerance</tooltip>
    <number>
      <maximum>360.0</maximum>
      <minimum>0.0</minimum>
    </number>
  </column>
</table>

=== harlantc/obscycle/prop/gov/sao/asc/obsed/data/axafobstat..fast_procTable.xml
<?xml version="1.0" encoding="us-ascii"?>

<!DOCTYPE table SYSTEM "table.dtd">

<table name="axafobstat..fast_proc" key="obsid">
  <column name="obsid">
    <type>INTEGER</type>
    <tooltip>Observation Identifier</tooltip>
  </column>
  <column name="status">
    <type>STRING</type>
    <tooltip>Fast Processing Status</tooltip>
  </column>
  <column name="comment">
    <type>STRING</type>
    <tooltip>Fast Processing Comments </tooltip>
  </column>
  <column name="last_updated">
    <type>DATE</type>
    <tooltip>Fast Processing Last Modified Date</tooltip>
  </column>
</table>
