=== harlantc/obscycle/prop/gov/sao/asc/obsed/data/table.dtd
<?xml version="1.0" encoding="us-ascii"?>

<!ELEMENT table (column+)>
<!ATTLIST table name ID #REQUIRED>
<!ATTLIST table key CDATA #REQUIRED>

<!ELEMENT column (type, tooltip, foreignKeyTable*, number?, choices?, constraint*)>
<!ATTLIST column name ID #REQUIRED>
<!ELEMENT type (#PCDATA)>
<!ELEMENT tooltip (#PCDATA)>
<!ELEMENT foreignKeyTable (#PCDATA)>
<!ELEMENT number (maximum?, minimum?, format?)>
<!ELEMENT maximum (#PCDATA)>
<!ELEMENT minimum (#PCDATA)>
<!ELEMENT format (#PCDATA)>
<!ELEMENT choices (item)+>
<!ELEMENT item (#PCDATA)>

<!ELEMENT constraint (#PCDATA)>

=== harlantc/obscycle/prop/gov/sao/asc/obsed/data/mpTable.xml
<?xml version="1.0" encoding="us-ascii"?>

<!DOCTYPE table SYSTEM "table.dtd">

<table name="mp" key="obsid">
  <column name="obsid">
    <type>INTEGER</type>
    <tooltip>Observation Identifier</tooltip>
  </column>
  <column name="counter">
    <type>INTEGER</type>
    <tooltip>Counter</tooltip>
  </column>
  <column name="seq_nbr">
    <type>STRING</type>
    <tooltip>Sequence Number</tooltip>
  </column>
  <column name="mp_priority">
    <type>INTEGER</type>
    <tooltip>Mission Planning Priority</tooltip>
  </column>
  <column name="mp_roll">
    <type>DOUBLE</type>
    <tooltip>Mission Planning Roll Angle</tooltip>
  </column>
  <column name="mp_roll_tolerance">
    <type>DOUBLE</type>
    <tooltip>Mission Planning Roll Tolerance</tooltip>
  </column>
  <column name="star_fidlight_file">
    <type>STRING</type>
    <tooltip>Star Fidlight File</tooltip>
  </column>
  <column name="lt_plan">
    <type>DATE</type>
    <tooltip>Start Date (with time set to midnight) in long term science plan</tooltip>
  </column>
  <column name="duration">
    <type>DOUBLE</type>
    <tooltip>Mission Planning Duration</tooltip>
  </column>
</table>

=== harlantc/obscycle/prop/gov/sao/asc/obsed/data/timereqTable.xml
<?xml version="1.0" encoding="us-ascii"?>

<!DOCTYPE table SYSTEM "table.dtd">

<table name="timereq" key="timereq_id">
  <column name="timereq_id">
    <type>INTEGER</type>
    <tooltip>Database index for timereq table</tooltip>
  </column>
  <column name="obsid">
    <type>INTEGER</type>
    <tooltip>Observation ID</tooltip>
  </column>
  <column name="ordr">
    <type>INTEGER</type>
    <tooltip>Order for timereq table entry per ObsId</tooltip>
  </column>
  <column name="window_constraint">
    <type>CHOICE</type>
    <tooltip>Flag indicating window constraint is required(Y) or  preferred(P)</tooltip>
    <choices>
      <item>Y</item>
      <item>P</item>
    </choices>
  </column>
  <column name="tstart">
    <type>DATE</type>
    <tooltip>Window Start Time (YYYY-MM-DD HH:MM:SS.SSS in GMT)</tooltip>
    <constraint>time</constraint>
  </column>
  <column name="tstop">
    <type>DATE</type>
    <tooltip>Window Stop Time (YYYY-MM-DD HH:MM:SS.SSS in GMT)</tooltip>
    <constraint>time</constraint>
  </column>

</table>

=== harlantc/obscycle/prop/gov/sao/asc/obsed/data/simTable.xml
<?xml version="1.0" encoding="us-ascii"?>

<!DOCTYPE table SYSTEM "table.dtd">

<table name="sim" key="obsid">
  <column name="obsid">
    <type>INTEGER</type>
    <tooltip>Observation Identifier</tooltip>
  </column>
  <column name="trans_offset">
    <type>DOUBLE</type>
    <tooltip>SIM Translation Offset (mm)</tooltip>
    <number>
      <maximum>126.621</maximum>
      <minimum>-190.5</minimum>
    </number>
  </column>
  <column name="focus_offset">
    <type>DOUBLE</type>
    <tooltip>SIM Focus Offset (mm)</tooltip>
  </column>
</table>

=== harlantc/obscycle/prop/gov/sao/asc/obsed/data/hrcparamTable.xml
<?xml version="1.0" encoding="us-ascii"?>

<!DOCTYPE table SYSTEM "table.dtd">

<table name="hrcparam" key="hrcid">
  <column name="hrcid">
    <type>INTEGER</type>
    <tooltip>HRC Identifier</tooltip>
  </column>
  <column name="si_mode">
    <type>STRING</type>
    <tooltip>Science Instrument Mode Mnemonic</tooltip>
  </column>
  <column name="trigger_level">
    <type>INTEGER</type>
    <tooltip>MCP signal event trigger threshold</tooltip>
    <number>
      <maximum>255</maximum>
      <minimum>-1</minimum>
    </number>
  </column>
  <column name="range_switch_level">
    <type>INTEGER</type>
    <tooltip>ADC amplifier switching threshold</tooltip>
    <number>
      <maximum>255</maximum>
      <minimum>-1</minimum>
    </number>
  </column>
  <column name="spect_mode">
    <type>CHOICE</type>
    <tooltip>HRC-S imaging/spectroscopy mode</tooltip>
    <choices>
	<item>DEF</item>
	<item>IMAGING</item>
	<item>NORMAL</item>
    </choices>
  </column>
  <column name="antico_enable">
    <type>CHOICE</type>
    <tooltip>Anticoincidence veto enabled</tooltip>
    <choices>
	<item>Y</item>
	<item>N</item>
	<item>D</item>
    </choices>
  </column>
  <column name="width_enable">
    <type>CHOICE</type>
    <tooltip>Width threshold veto enabled</tooltip>
    <choices>
	<item>Y</item>
	<item>N</item>
	<item>D</item>
    </choices>
  </column>
  <column name="width_threshold">
    <type>INTEGER</type>
    <tooltip>Max allowed event width for veto</tooltip>
    <number>
      <maximum>255</maximum>
      <minimum>-1</minimum>
    </number>
  </column>
  <column name="uld_enable">
    <type>CHOICE</type>
    <tooltip>Upper level discriminator veto enabled</tooltip>
    <choices>
	<item>Y</item>
	<item>N</item>
	<item>D</item>
    </choices>
  </column>
  <column name="upper_level_disc">
    <type>INTEGER</type>
    <tooltip>Upper level discriminator level</tooltip>
    <number>
      <maximum>255</maximum>
      <minimum>-1</minimum>
    </number>
  </column>
  <column name="blank_enable">
    <type>CHOICE</type>
    <tooltip>Region veto type</tooltip>
    <choices>
	<item>DEF</item>
	<item>CENTER</item>
	<item>EDGE</item>
	<item>NONE</item>
    </choices>
  </column>
  <column name="u_blank_hi">
    <type>INTEGER</type>
    <tooltip>U axis region blanking upper boundary</tooltip>
    <number>
      <maximum>255</maximum>
      <minimum>-1</minimum>
    </number>
  </column>
  <column name="v_blank_hi">
    <type>INTEGER</type>
    <tooltip>V axis region blanking upper boundary</tooltip>
    <number>
      <maximum>255</maximum>
      <minimum>-1</minimum>
    </number>
  </column>
  <column name="u_blank_lo">
    <type>INTEGER</type>
    <tooltip>U axis region blanking lower boundary</tooltip>
    <number>
      <maximum>255</maximum>
      <minimum>-1</minimum>
    </number>
  </column>
  <column name="v_blank_lo">
    <type>INTEGER</type>
    <tooltip>V axis region blanking lower boundary</tooltip>
    <number>
      <maximum>255</maximum>
      <minimum>-1</minimum>
    </number>
  </column>
  <column name="py_shutter_position">
    <type>INTEGER</type>
    <tooltip>+Y focus shutter position</tooltip>
    <number>
      <maximum>65535</maximum>
      <minimum>-1</minimum>
    </number>
  </column>
  <column name="my_shutter_position">
    <type>INTEGER</type>
    <tooltip>-Y focus shutter position</tooltip>
    <number>
      <maximum>65535</maximum>
      <minimum>-1</minimum>
    </number>
  </column>
  <column name="hrc_zero_block">
    <type>BOOLEAN</type>
    <tooltip>HRC zero order blocking</tooltip>
  </column>
  <column name="timing_mode">
    <type>BOOLEAN</type>
    <tooltip>HRC timing mode</tooltip>
  </column>
</table>
