=== harlantc/obscycle/prop/gov/sao/asc/obsed/data/table.dtd
<?xml version="1.0" encoding="us-ascii"?>

<!ELEMENT table (column+)>
<!ATTLIST table name ID #REQUIRED>
<!ATTLIST table key CDATA #REQUIRED>

<!ELEMENT column (type, tooltip, foreignKeyTable*, number?, choices?, constraint*)>
<!ATTLIST column name ID #REQUIRED>
<!ELEMENT type (#PCDATA)>
<!ELEMENT tooltip (#PCDATA)>
<!ELEMENT foreignKeyTable (#PCDATA)>
<!ELEMENT number (maximum?, minimum?, format?)>
<!ELEMENT maximum (#PCDATA)>
<!ELEMENT minimum (#PCDATA)>
<!ELEMENT format (#PCDATA)>
<!ELEMENT choices (item)+>
<!ELEMENT item (#PCDATA)>

<!ELEMENT constraint (#PCDATA)>

=== harlantc/obscycle/prop/gov/sao/asc/obsed/data/view_grantsTable.xml
<?xml version="1.0" encoding="us-ascii"?>

<!DOCTYPE table SYSTEM "table.dtd">

<table name="view_grants" key="grant_id">
  <column name="grant_id">
    <type>INTEGER</type>
    <tooltip>Database index for view_grants </tooltip>
  </column>
  <column name="prop_num">
    <type>STRING</type>
    <tooltip>Associated proposal number </tooltip>
  </column>
  <column name="grant_number">
    <type>STRING</type>
    <tooltip>Grant number </tooltip>
  </column>
  <column name="grant_type">
    <type>STRING</type>
    <tooltip>Grant type </tooltip>
  </column>
  <column name="grant_ao">
    <type>STRING</type>
    <tooltip>Grant AO (proposal cycle) </tooltip>
  </column>
  <column name="grantor">
    <type>STRING</type>
    <tooltip>Grantor</tooltip>
  </column>
  <column name="grant_amount">
    <type>DOUBLE</type>
    <tooltip>Grant Amount</tooltip>
  </column>
  <column name="title">
    <type>DOUBLE</type>
    <tooltip>Proposal Title</tooltip>
  </column>
  <column name="abstract">
    <type>DOUBLE</type>
    <tooltip>Proposal Abstract</tooltip>
  </column>
</table>

=== harlantc/obscycle/prop/gov/sao/asc/obsed/data/acisparamTable.xml
<?xml version="1.0" encoding="us-ascii"?>

<!DOCTYPE table SYSTEM "table.dtd">

<table name="acisparam" key="acisid">
  <column name="acisid">
    <type>INTEGER</type>
    <tooltip>ACIS Identifier</tooltip>
  </column>
  <column name="exp_mode">
    <type>CHOICE</type>
    <tooltip>Exposure Mode</tooltip>
    <choices>
      <item>TE</item>
      <item>CC</item>
    </choices>
  </column>
  <column name="dropped_chip_count">
    <type>INTEGER</type>
    <tooltip>Dropped Chip Count</tooltip>
  </column>
  <column name="ccdi0_on">
    <type>CHOICE</type>
    <tooltip>CCD I0 Flag (On/Off)</tooltip>
    <choices>
      <item>Y</item>
      <item>N</item>
      <item>O1</item>
      <item>O2</item>
      <item>O3</item>
      <item>O4</item>
      <item>O5</item>
    </choices>
  </column>
  <column name="ccdi1_on">
    <type>CHOICE</type>
    <tooltip>CCD I1 Flag </tooltip>
    <choices>
      <item>Y</item>
      <item>N</item>
      <item>O1</item>
      <item>O2</item>
      <item>O3</item>
      <item>O4</item>
      <item>O5</item>
    </choices>
  </column>
  <column name="ccdi2_on">
    <type>CHOICE</type>
    <tooltip>CCD I2 Flag </tooltip>
    <choices>
      <item>Y</item>
      <item>N</item>
      <item>O1</item>
      <item>O2</item>
      <item>O3</item>
      <item>O4</item>
      <item>O5</item>
    </choices>
  </column>
  <column name="ccdi3_on">
    <type>CHOICE</type>
    <tooltip>CCD I3 Flag </tooltip>
    <choices>
      <item>Y</item>
      <item>N</item>
      <item>O1</item>
      <item>O2</item>
      <item>O3</item>
      <item>O4</item>
      <item>O5</item>
    </choices>
  </column>
  <column name="ccds0_on">
    <type>CHOICE</type>
    <tooltip>CCD S0 Flag </tooltip>
    <choices>
      <item>Y</item>
      <item>N</item>
      <item>O1</item>
      <item>O2</item>
      <item>O3</item>
      <item>O4</item>
      <item>O5</item>
    </choices>
  </column>
  <column name="ccds1_on">
    <type>CHOICE</type>
    <tooltip>CCD S1 Flag </tooltip>
    <choices>
      <item>Y</item>
      <item>N</item>
      <item>O1</item>
      <item>O2</item>
      <item>O3</item>
      <item>O4</item>
      <item>O5</item>
    </choices>
  </column>
  <column name="ccds2_on">
    <type>CHOICE</type>
    <tooltip>CCD S2 Flag </tooltip>
    <choices>
      <item>Y</item>
      <item>N</item>
      <item>O1</item>
      <item>O2</item>
      <item>O3</item>
      <item>O4</item>
      <item>O5</item>
    </choices>
  </column>
  <column name="ccds3_on">
    <type>CHOICE</type>
    <tooltip>CCD S3 Flag </tooltip>
    <choices>
      <item>Y</item>
      <item>N</item>
      <item>O1</item>
      <item>O2</item>
      <item>O3</item>
      <item>O4</item>
      <item>O5</item>
    </choices>
  </column>
  <column name="ccds4_on">
    <type>CHOICE</type>
    <tooltip>CCD S4 Flag </tooltip>
    <choices>
      <item>Y</item>
      <item>N</item>
      <item>O1</item>
      <item>O2</item>
      <item>O3</item>
      <item>O4</item>
      <item>O5</item>
    </choices>
  </column>
  <column name="ccds5_on">
    <type>CHOICE</type>
    <tooltip>CCD S5 Flag </tooltip>
    <choices>
      <item>Y</item>
      <item>N</item>
      <item>O1</item>
      <item>O2</item>
      <item>O3</item>
      <item>O4</item>
      <item>O5</item>
    </choices>
  </column>
  <column name="bep_pack">
    <type>CHOICE</type>
    <tooltip>Event telemetry format</tooltip>
    <choices>
      <item>VF</item>
      <item>F</item>
      <item>F+B</item>
      <item>G</item>
    </choices>
  </column>
  <column name="onchip_sum">
    <type>BOOLEAN</type>
    <tooltip>On Chip Summing</tooltip>
  </column>
  <column name="onchip_row_count">
    <type>INTEGER</type>
    <tooltip>On Chip Row Count</tooltip>
    <number>
      <maximum>512</maximum>
      <minimum>1</minimum>
    </number>
  </column>
  <column name="onchip_column_count">
    <type>INTEGER</type>
    <tooltip>On Chip Column Count</tooltip>
    <number>
      <maximum>64</maximum>
      <minimum>1</minimum>
    </number>
  </column>
  <column name="most_efficient">
    <type>BOOLEAN</type>
    <tooltip>If true, use most efficient values for frame time</tooltip>
  </column>
  <column name="frame_time">
    <type>DOUBLE</type>
    <tooltip>Frame Time</tooltip>
    <number>
      <maximum>10.0</maximum>
      <minimum>0.0</minimum>
    </number>
  </column>
  <column name="subarray">
    <type>CHOICE</type>
    <tooltip>Sub Array</tooltip>
    <choices>
      <item>NONE</item>
      <item>CUSTOM</item>
    </choices>
  </column>
  <column name="subarray_start_row">
    <type>INTEGER</type>
    <tooltip>Sub Array Start Row</tooltip>
    <number>
      <maximum>925</maximum>
      <minimum>1</minimum>
    </number>
  </column>
  <column name="subarray_row_count">
    <type>INTEGER</type>
    <tooltip>Sub Array Row Count</tooltip>
    <number>
      <maximum>1024</maximum>
      <minimum>100</minimum>
    </number>
  </column>
  <column name="duty_cycle">
    <type>BOOLEAN</type>
    <tooltip>Alternating Exposure Readout</tooltip>
  </column>
  <column name="secondary_exp_count">
    <type>INTEGER</type>
    <tooltip>Number of secondary exposures</tooltip>
    <number>
      <maximum>15</maximum>
      <minimum>1</minimum>
    </number>
  </column>
  <column name="primary_exp_time">
    <type>DOUBLE</type>
    <tooltip>Primary Exposure Time</tooltip>
    <number>
      <maximum>10.0</maximum>
      <minimum>0.1</minimum>
    </number>
  </column>
  <column name="secondary_exp_time">
    <type>DOUBLE</type>
    <tooltip>Secondary Exposure Time</tooltip>
    <number>
      <maximum>10.0</maximum>
      <minimum>0.1</minimum>
    </number>
  </column>
  <column name="eventfilter">
    <type>BOOLEAN</type>
    <tooltip>Event Filter Flag</tooltip>
    <constraint>eventfilter</constraint>
  </column>
  <column name="eventfilter_lower">
    <type>DOUBLE</type>
    <tooltip>Event Filter Lower: minimum ACIS-I=.36, ACIS-S=.24</tooltip>
    <number>
      <maximum>15.0</maximum>
      <minimum>0.08</minimum>
    </number>
    <constraint>eventfilter</constraint>
  </column>
  <column name="eventfilter_higher">
    <type>DOUBLE</type>
    <tooltip>Event Filter Range: Upper Energy Threshold = (Lower Energy Threshold + Energy Filter Range) </tooltip>
    <number>
      <maximum>15.0</maximum>
      <minimum>0.1</minimum>
    </number>
    <constraint>eventfilter</constraint>
  </column>
  <column name="multiple_spectral_lines">
    <type>CHOICE</type>
    <tooltip>Logical value indicating whether or not more than 2 resolved spectral lines are expected in the brightest spectrum to be analyzed from this observation.
</tooltip>
  </column>
  <column name="spectra_max_count">
    <type>DOUBLE</type>
    <tooltip>Total maximum expected number of counts for any spectrum to be scientifically analyzed from this observation</tooltip>
    <number>
      <maximum>100000.0</maximum>
      <minimum>1.0</minimum>
    </number>
  </column>
</table>

=== harlantc/obscycle/prop/gov/sao/asc/obsed/data/mt_ephemTable.xml
<?xml version="1.0" encoding="us-ascii"?>

<!DOCTYPE table SYSTEM "table.dtd">

<table name="mt_ephem" key="obsid">
  <column name="obsid">
    <type>INTEGER</type>
    <tooltip>Observation Identifier</tooltip>
  </column>
  <column name="epoch">
    <type>DOUBLE</type>
    <tooltip>epoch</tooltip>
    <number>
      <maximum>69807.0</maximum>
      <minimum>15020.0</minimum>
      <format>0.0000</format>
    </number>
  </column>
  <column name="axis">
    <type>DOUBLE</type>
    <tooltip>semi-major axis</tooltip>
  </column>
  <column name="eccentricity">
    <type>DOUBLE</type>
    <tooltip>eccentricity</tooltip>
  </column>
  <column name="inclination">
    <type>DOUBLE</type>
    <tooltip>inclination</tooltip>
    <number>
      <maximum>180.0</maximum>
      <minimum>0.0</minimum>
      <format>0.0000</format>
    </number>
  </column>
  <column name="raan">
    <type>DOUBLE</type>
    <tooltip>right ascension of the ascending node</tooltip>
    <number>
      <maximum>360.0</maximum>
      <minimum>0.0</minimum>
      <format>0.0000</format>
    </number>
  </column>
  <column name="aop">
    <type>DOUBLE</type>
    <tooltip>argument of periastron</tooltip>
    <number>
      <maximum>360.0</maximum>
      <minimum>0.0</minimum>
      <format>0.0000</format>
    </number>
  </column>
  <column name="ma">
    <type>DOUBLE</type>
    <tooltip>mean anomaly at epoch</tooltip>
    <number>
      <maximum>360.0</maximum>
      <minimum>0.0</minimum>
      <format>0.0000</format>
    </number>
  </column>
</table>

=== harlantc/obscycle/prop/gov/sao/asc/obsed/data/soeTable.xml
<?xml version="1.0" encoding="us-ascii"?>

<!DOCTYPE table SYSTEM "table.dtd">

<table name="soe" key="row_id">
  <column name="row_id">
    <type>INTEGER</type>
    <tooltip>Row Identifier</tooltip>
  </column>
  <column name="obsid">
    <type>INTEGER</type>
    <tooltip>Observation Identifier</tooltip>
  </column>
  <column name="counter">
    <type>INTEGER</type>
    <tooltip>Counter</tooltip>
  </column>
  <column name="seq_nbr">
    <type>STRING</type>
    <tooltip>Sequence Number</tooltip>
  </column>
  <column name="obi">
    <type>INTEGER</type>
    <tooltip>Assigned observation interval</tooltip>
  </column>
  <column name="st_sched_date">
    <type>DATE</type>
    <tooltip>Scheduled Start Time</tooltip>
  </column>
  <column name="end_sched_date">
    <type>DATE</type>
    <tooltip>Scheduled End Time</tooltip>
  </column>
  <column name="sched_exp_time">
    <type>DOUBLE</type>
    <tooltip>Scheduled Exposure Time</tooltip>
  </column>
  <column name="soe_roll">
    <type>DOUBLE</type>
    <tooltip>Scheduled Roll Angle</tooltip>
  </column>
  <column name="quat0">
    <type>DOUBLE</type>
    <tooltip>Quaternion 0</tooltip>
    <number>
      <format>0.000000</format>
    </number>
  </column>
  <column name="quat1">
    <type>DOUBLE</type>
    <tooltip>Quaternion 1</tooltip>
    <number>
      <format>0.000000</format>
    </number>
  </column>
  <column name="quat2">
    <type>DOUBLE</type>
    <tooltip>Quaternion 2</tooltip>
    <number>
      <format>0.000000</format>
    </number>
  </column>
  <column name="quat3">
    <type>DOUBLE</type>
    <tooltip>Quaternion 3</tooltip>
    <number>
      <format>0.000000</format>
    </number>
  </column>
  <column name="rec_id">
    <type>STRING</type>
    <tooltip>Record Type</tooltip>
  </column>
  <column name="req_id">
    <type>STRING</type>
    <tooltip>Request ID</tooltip>
  </column>
</table>

=== harlantc/obscycle/prop/gov/sao/asc/obsed/data/view_piTable.xml
<?xml version="1.0" encoding="us-ascii"?>

<!DOCTYPE table SYSTEM "table.dtd">

<table name="view_pi" key="ocat_propid">
  <column name="ocat_propid">
    <type>INTEGER</type>
    <tooltip>Target Table Proposal Identifier</tooltip>
  </column>
  <column name="first">
    <type>STRING</type>
    <tooltip>Principal Investgator --- first name</tooltip>
  </column>
  <column name="last">
    <type>STRING</type>
    <tooltip>Principal Investigator --- last name</tooltip>
  </column>
</table>

=== harlantc/obscycle/prop/gov/sao/asc/obsed/data/ditherTable.xml
<?xml version="1.0" encoding="us-ascii"?>

<!DOCTYPE table SYSTEM "table.dtd">

<table name="dither" key="obsid">
  <column name="obsid">
    <type>INTEGER</type>
    <tooltip>Observation Identifier</tooltip>
  </column>
  <column name="y_amp">
    <type>DOUBLE</type>
    <tooltip>Y-axis Amplitude (degrees)</tooltip>
    <number>
      <minimum>0.0</minimum>
    </number>
  </column>
  <column name="y_freq">
    <type>DOUBLE</type>
    <tooltip>Y-axis Frequency (degrees/second)</tooltip>
    <number>
      <minimum>0.0</minimum>
    </number>
  </column>
  <column name="y_phase">
    <type>DOUBLE</type>
    <tooltip>Y-axis Phase (degrees)</tooltip>
    <number>
      <minimum>0.0</minimum>
    </number>
  </column>
  <column name="z_amp">
    <type>DOUBLE</type>
    <tooltip>Z-axis Amplitude (degrees)</tooltip>
    <number>
      <minimum>0.0</minimum>
    </number>
  </column>
  <column name="z_freq">
    <type>DOUBLE</type>
    <tooltip>Z-axis Frequency (degrees/second)</tooltip>
    <number>
      <minimum>0.0</minimum>
    </number>
  </column>
  <column name="z_phase">
    <type>DOUBLE</type>
    <tooltip>Z-axis Phase (degrees)</tooltip>
    <number>
      <minimum>0.0</minimum>
    </number>
  </column>
</table>

=== harlantc/obscycle/prop/gov/sao/asc/obsed/data/tooTable.xml
<?xml version="1.0" encoding="us-ascii"?>

<!DOCTYPE table SYSTEM "table.dtd">

<table name="too" key="tooid">
  <column name="tooid">
    <type>CHOICE</type>
    <tooltip>Unique identifier for TOO table</tooltip>
  </column>
  <column name="type">
    <type>CHOICE</type>
    <tooltip>TOO response type </tooltip>
  </column>
  <column name="start">
    <type>DOUBLE</type>
    <tooltip>Exact CXC response start time (days)</tooltip>
    <number>
      <maximum>360.0</maximum>
      <minimum>0.0</minimum>
    </number>
  </column>
  <column name="stop">
    <type>DOUBLE</type>
    <tooltip>Exact CXC response stop time (days)</tooltip>
    <number>
      <maximum>360.0</maximum>
      <minimum>0.0</minimum>
    </number>
  </column>
  <column name="alt_group_name">
    <type>STRING</type>
    <tooltip>Alternate target group name </tooltip>
  </column>
  <column name="alt_approved_cnt">
    <type>INTEGER</type>
    <tooltip>TOO Alternate target group approved trigger count</tooltip>
  </column>
  <column name="trig">
    <type>STRING</type>
    <tooltip>TOO Trigger Criteria</tooltip>
  </column>
  <column name="remarks">
    <type>STRING</type>
    <tooltip>TOO follow-up instructions</tooltip>
  </column>
  <column name="followup">
    <type>INTEGER</type>
    <tooltip>TOO number of followup observations</tooltip>
  </column>
</table>

=== harlantc/obscycle/prop/gov/sao/asc/obsed/data/prop_infoTable.xml
<?xml version="1.0" encoding="us-ascii"?>

<!DOCTYPE table SYSTEM "table.dtd">

<table name="prop_info" key="ocat_propid">
  <column name="ocat_propid">
    <type>INTEGER</type>
    <tooltip>ObsCat Proposal Identifier (prop_info)</tooltip>
  </column>
  <column name="proposal_id">
    <type>INTEGER</type>
    <tooltip>Proposal Identifier in proposal database</tooltip>
  </column>
  <column name="prop_num">
    <type>STRING</type>
    <tooltip>Proposal Number</tooltip>
  </column>
  <column name="title">
    <type>STRING</type>
    <tooltip>Proposal Title</tooltip>
  </column>
  <column name="description">
    <type>CHOICE</type>
    <tooltip>Subject Category/Description</tooltip>
  </column>
  <column name="proposal_type">
    <type>STRING</type>
    <tooltip>Proposal Type</tooltip>
  </column>
  <column name="piid">
    <type>CHOICE</type>
    <tooltip>Principal Investigator ID</tooltip>
  </column>
  <column name="aoid">
    <type>CHOICE</type>
    <tooltip>AO i.e. NRA cycle number (stored as an integer)</tooltip>
  </column>
  <column name="ao_str">
    <type>CHOICE</type>
    <tooltip>AO i.e. NRA cycle number (stored as a string)</tooltip>
    <constraint>aostr</constraint>
  </column>
  <column name="medium">
    <type>CHOICE</type>
    <tooltip>Storage/delivery media (tape/CD/etc)</tooltip>
    <choices>
      <item>WWW-ONLY</item>
      <item>2GBDAT</item>
      <item>4GBDAT</item>
      <item>2GB8MM</item>
      <item>5GB8MM</item>
      <item>CD-ROM</item>
      <item>CD-ROM,ZIPPED</item>
      <item>CD-ROM,UNZIPPED</item>
    </choices>
  </column>
  <column name="coi_contact">
    <type>BOOLEAN</type>
    <tooltip>Use Co-Investigator as point-of-contact?</tooltip>
    <constraint>coi</constraint>
  </column>
  <column name="coin_id">
    <type>INTEGER</type>
    <tooltip>Co-Investigator Identifier</tooltip>
    <constraint>coi</constraint>
  </column>
  <column name="coi_phone">
    <type>STRING</type>
    <tooltip>Co-Investigator Phone Number</tooltip>
    <constraint>coi</constraint>
  </column>
  <column name="joint">
    <type>CHOICE</type>
    <tooltip>Proposal submitted under joint Chandra policy?</tooltip>
  </column>
  <column name="xmm_approved_time">
    <type>DOUBLE</type>
    <tooltip>XMM approved time for joint proposal (ks)</tooltip>
    <number>
     <format>0.0000</format>
    </number>

  </column>
  <column name="hst_approved_time">
    <type>INTEGER</type>
    <tooltip>HST approved time for joint proposal (orbits)</tooltip>
  </column>
  <column name="noao_approved_time">
    <type>DOUBLE</type>
    <tooltip>NOAO approved time for joint proposal (nights)</tooltip>
    <number>
     <format>0.0000</format>
    </number>
  </column>
  <column name="nustar_approved_time">
    <type>DOUBLE</type>
    <tooltip>NuSTAR approved time for joint proposal (ks)</tooltip>
    <number>
     <format>0.0000</format>
    </number>
  </column>
  <column name="rxte_approved_time">
    <type>DOUBLE</type>
    <tooltip>RXTE approved time for joint proposal (ks)</tooltip>
    <number>
     <format>0.0000</format>
    </number>
  </column>
  <column name="nrao_approved_time">
    <type>DOUBLE</type>
    <tooltip>NRAO approved hours for joint proposal</tooltip>
    <number>
     <format>0.0000</format>
    </number>
  </column>
  <column name="spitzer_approved_time">
    <type>DOUBLE</type>
    <tooltip>Spitzer Space Telescope approved time for joint proposal (hours)</tooltip>
    <number>
     <format>0.0000</format>
    </number>
  </column>
  <column name="suzaku_approved_time">
    <type>DOUBLE</type>
    <tooltip>Suzaku approved time for joint proposal (ksec)</tooltip>
    <number>
     <format>0.0000</format>
    </number>
  </column>
  <column name="swift_approved_time">
    <type>DOUBLE</type>
    <tooltip>Swift approved time for joint proposal (ksec)</tooltip>
    <number>
     <format>0.0000</format>
    </number>
  </column>

  <column name="abstract">
    <type>STRING</type>
    <tooltip>Proposal Abstract</tooltip>
  </column>
</table>
